### PR TITLE
io: merge eval_ast into eval, add DEBUG-EVAL

### PR DESCRIPTION
**Pull request by asarhaddon**
The self-hosted tests fail, for apparently unrelated reasons (the first readline fails in step0). Were they failing before?

### CODE REVIEW

**Comment by kanaka** [comment]
@asarhaddon @dubek The update to the version of io in the Dockerfile appears to have completed self-hosted tests successfully: https://github.com/kanaka/mal/actions/runs/11327008274/job/31497159120 The io repo hasn't changed from the time when @dubek did the update to when the pushed image would have been pushed (although it would have been a different instance of the build but of the same sources).

Maybe it's some sort of temperamental GC related issue? When I build and run locally with it works.

**Comment by asarhaddon** [comment]
Sorry, I have no clue and miss motivation to investigate this issue.

**Comment by asarhaddon** [comment]
A single comma was causing a crash reported in an unrelated module...
And now that this is solved, a self-hosting issue.
I have no clue for now, but I suggest to move this enigm from #699 to #662.

**Comment by kanaka** [comment]
@asarhaddon sounds like a reasonable plan. I've added io to #662

**Pull request merged**
