### PR TITLE
Fix first and rest with nil argument

### PR DESCRIPTION
**Pull request by dubek**
Expected behaviour:

```
(first nil)
;=>nil
(rest nil)
;=>()
```

Initially includes fix for 6 impls, soon I'll add the entire list. This is still WIP, don't merge yet please.

- [x] awk
- [x] c
- [x] cpp
- [x] coffee
- [x] cs
- [x] elixir
- [x] erlang
- [x] es6
- [x] factor
- [x] fsharp
- [x] go
- [x] groovy
- [x] guile
- [x] haskell
- [x] haxe
- [x] java
- [x] js
- [x] julia
- [x] kotlin
- [x] lua
- [x] matlab
- [x] miniMAL
- [x] perl
- [x] php
- [x] ps
- [x] python
- [x] r
- [x] rpython
- [x] ruby
- [x] rust
- [x] scala
- [x] swift
- [x] vb
- [x] vimscript

### CODE REVIEW

**Comment by kanaka** [comment]
I'll take matlab and rpython.

**Comment by kanaka** [comment]
Just pushed rpython and matlab. I'll mark them off when travis passes for those (https://travis-ci.org/kanaka/mal/builds/106806400)

**Comment by kanaka** [comment]
Swift passed (https://travis-ci.org/kanaka/mal/jobs/106781337) so I marked that complete too.

**Comment by kanaka** [comment]
@dubek BTW, do you use IRC at all? I hang out in #mal on freenode if you're interested.

**Comment by dubek** [comment]
groovy, java, scala and kotlin fixed. All green, at last.

**Pull request merged**
