### PR TITLE
Kotlin

### PR DESCRIPTION
**Pull request by ivern**
Theres some cleanup I want to do (mainly tidying up the steps and cleaning up the types hierarchy), but I'm setting up the PR now so I can get any additional needed feedback.

Some comments:
* The latest version of kotlin available on Homebrew won't do.  Use this instead, or newer: https://github.com/JetBrains/kotlin/releases/tag/build-1.0.0-beta-1038.  Unzipping kotlin-compiler and setting KOTLIN_HOME and PATH should be sufficient.
* You're going to get a warning about an unnecessary cast when compiling.  I don't have a way around this, as there appears to be a bug in the Kotlin compiler--if I remove the "unnecessary" cast, then I get a type error.  I don't think this is a major problem, as it's just a compile time warning with no runtime effect.
* As far as I can tell, all required and optional tests pass in both direct and self-hosted mode.  I added a few new tests to catch some of the stuff that tripped me (mostly, my terrible implementation of swap!)
* I didn't bother implementing readline, as I used rlwrap for development and it gives me everything a readline integration would.  `rlwrap -H ~/.mal-history java -jar stepA_mal.jar` does the trick...available in pretty much any decent Linux package manager and Homebrew.

Any suggestions are welcome.  Thanks for making this awesome project!

### CODE REVIEW

**Comment by kanaka** [comment]
Apart from the cleanup you already mentioned, especially the difference between step5-stepA from the first steps, I think it looks good (Kotlin is new to me so I can't really determine if it is good Kotlin code).

A couple of other minor things:

* could you make a Dockerfile for Kotlin (probably based on the Java one). I'll use that to activate Kotlin in travis.
* bump the count in the README.

**Comment by kanaka** [comment]
BTW, if you don't have experience with docker or a place to run it to test it, don't worry about it, I can do that. Doesn't sound like the kotlin install process is too complicated so I should be able to figure it out.

**Comment by kanaka** [comment]
Oh, one more thing. This is still a TODO in the guide, but if you have a chance could you also implement a time-ms function that returns the current milliseconds since epoch. I use that to be able to do a very rough benchmarking between implementations.

**Comment by ivern** [comment]
The big change from step4 to step5 was that TCO made my step4 approach to eval cumbersome as I started needing to replace the values of ast and env.  There may be a way to make eval look way cleaner with TCO, but I'm not seeing it right now (I'm fairly new to Kotlin as well.)

I'll make the other changes now.  I think I can figure out Docker, I've it installed but haven't done a whole lot with it yet.  Gimme a few.

**Comment by ivern** [comment]
Just pushed a docker file, which seems to work.  Running `docker run -v $HOME/projects/mal/:/mal -w /mal -t mal-kotlin make test^kotlin` after creating a mal-kotlin image from it runs all tests and whatnot.

**Comment by ivern** [comment]
Hrm, I'm missing something.  Running make -C kotlin from Docker works, but trying to run the tests directly fails to compile them.  So right now it's a two step process of making, then running.  Outside docker, running the tests builds them as expected.

**Comment by kanaka** [comment]
@ivern It actually worked fine for me. After building the docker image, I ran this:

```
docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-kotlin make test^kotlin
```

Which did both the build and ran the tests successfully. I use $(id -u) since my mal directory is a NFS mount and doesn't allow root access. I would expect permission errors rather than failure to build.

**Comment by kanaka** [comment]
@ivern I've gone ahead and merged. Also, I was able to run all tests including self-hosted tests using the container.

I pushed a minor change to the Dockerfile so that layers from the Java Dockerfile are re-used from the Java Dockerfile (given that the openjdk layer is fairly large and takes a while to build.

Feel free to keep cleaning up things until you're happy with it and I'll continue merging things in.

At some point, please announce your implementation by tweeting it and I'll retweet it (or I can just do it if you would prefer). Also, in case you aren't aware yet, there is also #mal on freenode IRC. It's pretty quite, but a few people involved in mal hang out there.

Thanks for the implementation. Yours is 42 which is an awesome number to have :-) Also, it's just in time for the presentation at midwest.io that I'll be doing about mal.

**Comment by kanaka** [comment]
@ivern do you want to tweet to announce your implementation?

**Comment by kanaka** [comment]
@ivern I'm getting antsy to announce this :-). You want to tweet it (and I'll retweet) or should I?

**Pull request merged**
