### PR TITLE
Improve python.2 performance on perf3 benchmark by 77%

### PR DESCRIPTION
**Pull request by epylar**
Performance is improved about 77% on my system
    
Optimizations:
* remove use of `ABC`/`abstractmethod`
* start new environments with copy of `outer`; no need to `find(key)`
* run with asserts off

### CODE REVIEW

**Comment by epylar** [comment]
I'm not sure if the `outer` optimization is a good idea (uses more space?).

**Comment by epylar** [comment]
Also unsure why GitHub is showing the #459 merge here even after resetting my origin to upstream and rebasing.

**Comment by epylar** [comment]
OK, I'll stop experimenting on this PR and figure out how to do proper PRs across forks on a dummy repo.

**Comment by kanaka** [comment]
Looks like you have it entangled with some of the bash-5 work you were doing. I was able to fix the epylar:perf-python.2 branch you have pushed like this:

```
git rebase 2fe64cd
```

The hash ```2fe64cd``` is the one for the bash-5 fix that is upstream in master.

**Comment by epylar** [comment]
@kanaka rebase 2fe64cd and then push --force-with-lease seems to have resolved it

**Comment by epylar** [comment]
@kanaka I also noticed running either of the Python implementations in pypy produced a huge speedup for perf3. For the main `python` implementation, it ran about 6.6 times faster.

**Comment by kanaka** [comment]
Merged. From the travis results it does seem that the implementation now has the same or better performance than the regular python3 implement. Yes, pypy is very fast. Even faster is mal implementation in rpython (pypy itself is implemented using rpython). I would be happy to take a PR that added an additional run mode for the python and python.2 implementation that runs with pypy. This would involve adding pypy to the Docker images, a mode variable for python.2 (python__2_MODE with the recent path), and adding a Travis run mode for each.

**Pull request merged**
