### PR TITLE
Test equality of other kinds of empty list

### PR DESCRIPTION
**Pull request by bjh21**
In #513, @dubek noted two additional ways to make empty lists in fantom that compare different from an empty list made by evaluating an empty list.  This adds tests for those, along with another two that might fail similarly (but don't in fantom).

### CODE REVIEW

**Comment by dubek** [comment]
Consider adding also: `(= {} (hash-map))` in step 9.

**Comment by bjh21** [comment]
@dubek: That's a good plan.  I've added it and another obvious one.

**Comment by dubek** [comment]
Travis looks OK except fantom (as expected). Fantom fixes are in #520 .

**Comment by kanaka** [comment]
Tests look good. Merged.

**Pull request merged**
