### PR TITLE
Haskell: make the code more readable and idiomatic

### PR DESCRIPTION
**Pull request by asarhaddon**

### CODE REVIEW

**Comment by kanaka** [comment]
@asarhaddon I assume that since you still have the FIXME commit removing the builds for other implementations that you don't intend me to merge this yet? Also, there is a typo in one of the commits: "white" -> "while". I did a quick review of the changes and they seem reasonable overall.

**Comment by asarhaddon** [comment]
I must confess that I have been abusing this PR in order to test the changes (some portability issues were not visible on my machine). Now that you have approved the changes, I have prepared a proper PR.

**Comment by kanaka** [comment]
@asarhaddon that's no problem. Travis isn't particular flexible in that regard. In the future just label the PR with a WIP prefix so I don't accidentally merge it before it's ready.

Merged.

**Comment by dubek** [comment]
@kanaka @asarhaddon Github now has [draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) which disallow merging. Haven't used them yet but might be useful for such cases.

**Comment by asarhaddon** [comment]
Thanks for the hint, that would probably have been the right tool.

**Pull request merged**
