### PR TITLE
Livescript implementation

### PR DESCRIPTION
**Pull request by c0deaddict**
I've recently followed the mal guide to build an implementation in Livescript. It was really much fun! Thanks for the great guide!

I noticed there is an open pull request for another Livescript implementation, but the last comments on that thread are from 2015. So I thought I'll give it a try.

What do you think about my Livescript implementation?

### CODE REVIEW

**Comment by kanaka** [comment]
Implementation looks good! Glad you enjoyed it. I've verified that both regular and self-hosted tests pass. However, there are a few minor things before I merge:

- Running the following from the top-level should work: `make -C livescript clean && make test^livescript`. In order to make that work there are some missing dependencies in the Makefile:

```patch
diff --git a/livescript/Makefile b/livescript/Makefile
index 080d572..07c91d2 100644
--- a/livescript/Makefile
+++ b/livescript/Makefile
@@ -13,8 +13,19 @@ all: node_modules $(BINS)
 node_modules:
        npm install
 
-%.js: %.ls
+%.js: %.ls node_modules
        $(LSC) -d -c $(@:%.js=%.ls)
 
+step1_read_print.js: utils.js reader.js printer.js
+step2_eval.js: utils.js reader.js printer.js
+step3_env.js: utils.js reader.js printer.js env.js
+step4_if_fn_do.js: utils.js reader.js printer.js env.js core.js
+step5_tco.js: utils.js reader.js printer.js env.js core.js
+step6_file.js: utils.js reader.js printer.js env.js core.js
+step7_quote.js: utils.js reader.js printer.js env.js core.js
+step8_macros.js: utils.js reader.js printer.js env.js core.js
+step9_try.js: utils.js reader.js printer.js env.js core.js
+stepA_mal.js: utils.js reader.js printer.js env.js core.js
+
 clean:
        rm -f $(BINS)
```

- Please add the following Dockerfile to your directory:

```
FROM ubuntu:xenial
MAINTAINER Joel Martin <github@martintribe.org>

##########################################################
# General requirements for testing or common across many
# implementations
##########################################################

RUN apt-get -y update

# Required for running tests
RUN apt-get -y install make python

# Some typical implementation and test requirements
RUN apt-get -y install curl libreadline-dev libedit-dev

RUN mkdir -p /mal
WORKDIR /mal

##########################################################
# Specific implementation requirements
##########################################################

# For building node modules
RUN apt-get -y install g++

# Add nodesource apt repo config for 7.X
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -

# Install nodejs
RUN apt-get -y install nodejs
```

- Activate your build for travis testing by adding it to `.travis.yml`. Once you do that, the next time you push to github, travis should test your implementation. I've already built and pushed a docker image built using the above Dockerfile to the docker hub so it should be able to be tested as soon as it's enabled.

- Add your implementation to the README citing yourself as the creator (see typescript as an example). Also, bump the implementation count.

- [Optional] Add `stats` and `stats-lisp` rules to your Makefile. `coffee/Makefile` probably has a pretty close rules for counting comment/blank lines. I can do this afterwards if you don't want to.

- Push your changes. Once travis confirms everything passes, then I'll merge.

- [Optional] Write a blog post about your experience and interesting things you learned. This is totally optional of course, but if you were thinking about doing this anyways, don't wait too long or you'll start to forget things you learned that might be worth sharing.

- Send a tweet about your implementation (with a link to blog post if you decide to do that). Link to your tweet here and I'll retweet it.

**Comment by dubek** [comment]
yay! new implementation!

**Comment by c0deaddict** [comment]
Thanks for your feedback @kanaka. I've implemented the changes. I'm not quite sure what the regex does in stats and stats-lisp, but I copied it from the coffeescript implementation and it appears to work.

I'll send a tweet later tonight, and i'll think about making a blog post. Thanks again for this wonderful project. I'm thinking about doing another implementation in another language :-)

**Comment by kanaka** [comment]
I stopped Travis for the other implementations (so we don't have to wait a couple hours). I had to make a minor Dockerfile update, but now things pass: https://travis-ci.org/kanaka/mal/jobs/235731614

**Comment by c0deaddict** [comment]
https://twitter.com/c0deaddict/status/867659519521943553

**Comment by kanaka** [comment]
@c0deaddict I note that you have some Elm background. Surprisingly, Elm is currently missing as a mal implementation. Interested in tackling that next? You'll might have to deal with some hassle around command line execution. E.g. https://github.com/jfairbank/run-elm

**Comment by c0deaddict** [comment]
That would be interesting, i'm on it!

**Pull request merged**
