### PR TITLE
fix typo in guide.md step 7

### PR DESCRIPTION
**Pull request by fabjan**
I'm pretty sure this is a typo at least.

### CODE REVIEW

**Comment by alimpfard** [comment]
I noticed it too https://github.com/kanaka/mal/pull/533/commits/c3781c2438ddb15cf4cd401a70e6014c2a584de2, it's definitely a typo.

**Comment by wasamasa** [comment]
I'm not 100% sure about it since there's been many changes to quasiquoting and I haven't looked into them yet. @asarhaddon Could you please take a quick look?

**Comment by fabjan** [comment]
Here is why I think it's a typo:

1. This paragraph is about adding support for vectors, and with "unquote", it reflects how lists work.
2. Other implementations seem to treat vectors and lists without "unquote" the same (I looked art C, Clojure and OCaml).
3. My SML implementation failed tests until I used the same code as for lists not starting with "unquote".

but it would of course be great with input from someone who knows for sure.

**Comment by asarhaddon** [comment]
You are right, this should be "a list not starting with `unquote`" instead of "a list not starting with `quote`".

**Comment by kanaka** [comment]
Sorry for the slow reply everyone. Without actually planning to do this, I basically ended up taking a break from open-source/mal/free-time work for the past year. I'll blame it on the pandemic. I had a paid job shift recently so I may have some more time in the next few weeks to catch up on some mal stuff that I've been putting off for a while.

**Pull request merged**
