### PR TITLE
Update elm implementation, fix keywords and metadata, merge eval

### PR DESCRIPTION
**Pull request by asarhaddon**
Hello.
The first commit updates the elm implementation for 0.19.1. The docker file describes my configuration but should probably be checked on an actual image.
The two following commits fix the last failing optional tests.
The two last commits should be part of #592, but required 0.19.1 for testing.

### CODE REVIEW

**Comment by asarhaddon** [comment]
The tests were passing on my machine, so they will probably also pass in an updated Docker image.

**Comment by asarhaddon** [comment]
Hello.
For some reason, the installation of the tzdata package interactively asks the geographical area, so the actual tests do not even start.  I have no idea how to debug this.

**Comment by kanaka** [comment]
Yeah, seems like it's a behavior that started midstream in an Ubuntu release. The trick is this:
```
RUN DEBIAN_FRONTEND=noninteractive apt-get -y ...
```

**Comment by kanaka** [comment]
Update with fixed the Dockerfile issue and a Makefile bug (probably search/replace issue). Merged these commits from my own branch so closing this.

**Pull request closed without merging**
