### PR TITLE
Fix handling of literal empty list in several impls

### PR DESCRIPTION
**Pull request by dubek**
Fix handling of `()` (without quoting) which fails on most implementations. See #190 for the original bug report.

Currently this PR includes a test (step3), addition to `process/*.txt` files and a fix for:

* coffee
* js
* mal
* ruby
* tcl
* vimscript
* c (segfault)
* lua
* racket
* perl
* go (panic)
* elixir
* ocaml
* miniMAL
* haskell
* fsharp
* php
* io
* nim
* julia
* guile
* kotlin
* clojure
* es6
* ps
* forth

Most of them required a fix in the `EVAL` function in step3-stepA and the `is_macro_call` function in step8-stepA.

Here are the remaining implementations according to Travis (elisp fixed in a separate PR):

- [x] ada
- [x] bash
- [x] crystal
- [x] d
- [x] factor
- [x] groovy
- [x] haxe
- [x] make
- [x] matlab
- [x] objpascal
- [x] objc
- [x] scala
- [x] swift3

### CODE REVIEW

**Comment by dubek** [comment]
@zmower Can you take a look a at a fix for Ada for this issue (#190 / #194) ?

**Comment by dubek** [comment]
matlab/objc/objpascal/swift3 - fixed by @kanaka. 

process/step2_eval.txt updated.

ada - in progress by @zmower in https://github.com/dubek/mal/pull/3 .

**Comment by dubek** [comment]
Merged Ada impl fix by @zmower .

**Comment by kanaka** [comment]
@dubek I sent a new PR to your PR that should address the final issues with erlang, factor and rust. I also went ahead and merged @wasamasa elisp fix (since it shouldn't break anything). Once you merge my PR and this PR checks out with Travis I'll merge the rest.

**Comment by dubek** [comment]
@kanaka Merged your erlang+factor+rust fixes. I expect all impls to pass except elisp (not on this branch).

**Comment by kanaka** [comment]
@dubek merged. Thanks for doing most of that!

**Pull request merged**
