### PR TITLE
Added GNU Guile implementation

### PR DESCRIPTION
**Pull request by NalaGinrut**

### CODE REVIEW

**Comment by kanaka** [comment]
@NalaGinrut very cool. I'm having some issues testing it. I'm using guile-2.0 on Ubuntu 14.04. 

Step 0 test pass. Step 1 tests gives this error:
```
...
Testing read of strings
TEST: "abc" -> ['','"abc"']
Exception: IOError(5, 'Input/output error')
Output before exception:
"abc"
Backtrace:
In ice-9/boot-9.scm:
 157: 12 [catch #t #<catch-closure 10de400> ...]
In unknown file:
   ?: 11 [apply-smob/1 #<catch-closure 10de400>]
In ice-9/boot-9.scm:
  63: 10 [call-with-prompt prompt0 ...]
In ice-9/eval.scm:
 432: 9 [eval # #]
In ice-9/boot-9.scm:
2320: 8 [save-module-excursion #<procedure 1110c00 at ice-9/boot-9.scm:3961:3 ()>]
3968: 7 [#<procedure 1110c00 at ice-9/boot-9.scm:3961:3 ()>]
In unknown file:
   ?: 6 [load-compiled/vm "/home/joelm/.cache/guile/ccache/2.0-LE-8-2.0/data2/joelm/personal/programming/mal-NalaGinrut/guile/step1_read_print.scm.go"]
In /data2/joelm/personal/programming/mal-NalaGinrut/guile/../guile/step1_read_print.scm:
  33: 5 [REPL]
In ice-9/boot-9.scm:
 157: 4 [catch mal-error ...]
In /data2/joelm/personal/programming/mal-NalaGinrut/guile/../guile/step1_read_print.scm:
  26: 3 [PRINT "abc"]
In ../guile/printer.scm:
  50: 2 [pr_str "abc" #t]
In ice-9/regex.scm:
 131: 1 [string-match "^\u029e(.*)" "abc"]
In unknown file:
   ?: 0 [make-regexp "^\u029e(.*)"]

ERROR: In procedure make-regexp:
ERROR: In procedure make-regexp: Invalid preceding regular expression

make: *** [test^guile^step1] Error 1
```

That looks like a regex issue of some sort.

Step 2 tests fail with a different error:
```
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /data2/joelm/personal/programming/mal-NalaGinrut/guile/../guile/step2_eval.scm
;;; WARNING: compilation of /data2/joelm/personal/programming/mal-NalaGinrut/guile/../guile/step2_eval.scm failed:
;;; ERROR: no code for module (srfi srfi-43)
Backtrace:
In ice-9/boot-9.scm:
 157: 15 [catch #t #<catch-closure 1151400> ...]
In unknown file:
   ?: 14 [apply-smob/1 #<catch-closure 1151400>]
In ice-9/boot-9.scm:
  63: 13 [call-with-prompt prompt0 ...]
In ice-9/eval.scm:
 432: 12 [eval # #]
In ice-9/boot-9.scm:
2320: 11 [save-module-excursion #<procedure 1169c00 at ice-9/boot-9.scm:3961:3 ()>]
3968: 10 [#<procedure 1169c00 at ice-9/boot-9.scm:3961:3 ()>]
1645: 9 [%start-stack load-stack ...]
1650: 8 [#<procedure 12a6bd0 ()>]
In unknown file:
   ?: 7 [primitive-load "/data2/joelm/personal/programming/mal-NalaGinrut/guile/../guile/step2_eval.scm"]
In ice-9/eval.scm:
 505: 6 [#<procedure 101e620 at ice-9/eval.scm:499:4 (exp)> (import # # # ...)]
In ice-9/psyntax.scm:
1091: 5 [expand-top-sequence ((import (readline) (reader) ...)) () ...]
 976: 4 [scan ((import (readline) (reader) ...)) () ...]
 270: 3 [scan ((# # #) (# # #)) () (()) ...]
In ice-9/eval.scm:
 411: 2 [eval # ()]
In ice-9/boot-9.scm:
2786: 1 [resolve-interface (srfi srfi-43) #:select ...]
In unknown file:
   ?: 0 [scm-error misc-error #f "~A ~S" ("no code for module" (srfi srfi-43)) #f]

ERROR: In procedure scm-error:
ERROR: no code for module (srfi srfi-43)
```

Looks like maybe a missing guile module? Can you update the top level README to list what version of guile this works with an what additional modules are required (if any).

**Comment by NalaGinrut** [comment]
It's based on the cutting-edge Guile-2.1+
Please try this:
http://git.savannah.gnu.org/cgit/guile.git/snapshot/guile-50fcdfece306a437ebad326679245e206cfbe6b2.tar.gz

All the tests passed in my machine. But after readline enabled, there's problem. I intend to enable it to show you the problem.

**Comment by kanaka** [comment]
Gah! I think guile has the longest configure process I've ever seen (and I've seen a lot).

**Comment by kanaka** [comment]
Okay, let me know when you've figured it out. Yes, enabling the output in the mal in mal steps does help a lot. And debugging self-hosting issues is definitely mind bending and tough (too many levels of inception). When you find the issue, if it's something that the tests aren't already covering it would be great to have a regular test for it so that future implementors will discover the problem before they try and get to self-hosting.

If I get a chance in the next few days and you haven't already squashed the bug, I might take a look to see if I can narrow down issuel; I've tackled self-hosting a few times in the past ;-) BTW, have you implemented step6 file reading and just not pushed it yet? The following still doesn't do the right thing for me on master:

```
guile -L ../guile ../guile/stepA_mal.scm ../tests/incC.mal
Mal [guile]
user>
```

The correct behavior would be something like this:

```
guile -L ../guile ../guile/stepA_mal.scm ../tests/incC.mal
"incC.mal finished"
```

**Comment by NalaGinrut** [comment]
@kanaka Yes, please see the latest commits. I've already fixed the step3 bug. I encountered another bug in step7 self-hosting. Hope I can fix it soon, since I haven't implemented time counter for benchmark yet.

**Comment by kanaka** [comment]
@NalaGinrut I just pulled and tested again and it's looking really close. I think I only notice a couple of things that need to be cleanup up before merge:

- the argument processing code should start in step6-A, not just stepA.
- the printing of the host language should only happen in the REPL case. If the implementation is being used to run another program it shouldn't be printed out.

The two errors happening in self-host testing (metadata on collections) would be good to fix, but those last few tests are not a prerequisite for me to merge.

**Comment by kanaka** [comment]
@NalaGinrut just pulled and tried again. Self-hosting passes through step4, step6-8 fails, step9 and stepA run, however, they run exponentially more slowly than steps0-4. I know what's causing the slow execution: the first argument is not being stripped from *ARGV* when the sub-command is executed. This means, that what's actually happening when step9 and stepA are executed is that it is double self-hosting. In other words, the guile implementation of mal is running the mal implementation of mal which is again running the mal implementation of mal. In other words, because argument processing is broken in the guile implementation you are ending up with too many level of inception :-) I'm not sure why step6-8 are failing, but my guess is that it's related to the argument processing too.

**Comment by NalaGinrut** [comment]
@kanaka 6~8 fail because I set *ARGV* in interpreter mode, which should appear in REPL mode. I think it's passed now.

**Comment by kanaka** [comment]
@NalaGinrut excellent! Merged. I cleanup up the README a bit and bumped the language count to 33.

Only thing remaining is for you to tweet it to announce it (and let me know your twitter handle). If you don't have twitter account then let me know that too and I'll go ahead and tweet it myself.

**Comment by NalaGinrut** [comment]
@kanaka Thank you very much! My twitter account is 'nalaginrut', the same with my github account. Please feel free to mention it.
The last problem is I can't run "make perf^guile" to get a result. It seems halt very long time. I wonder if there's a bug.

**Comment by NalaGinrut** [comment]
@kanaka Alright, it's perfect now, here's a result comparing to Node.js implementation:
```
nalaginrut@Renee-desktop:mal> make perf^guile
----------------------------------------------
Performance test for guile:
Running: guile -L ../guile ../guile/stepA_mal.scm ../tests/perf1.mal
"Elapsed time: 2.0 msecs"
Running: guile -L ../guile ../guile/stepA_mal.scm ../tests/perf2.mal
"Elapsed time: 11.0 msecs"
Running: guile -L ../guile ../guile/stepA_mal.scm ../tests/perf3.mal
iters/s: 1430.6666666666667
nalaginrut@Renee-desktop:mal> make perf^js
----------------------------------------------
Performance test for js:
Running: node ../js/stepA_mal.js ../tests/perf1.mal
"Elapsed time: 5 msecs"
Running: node ../js/stepA_mal.js ../tests/perf2.mal
"Elapsed time: 15 msecs"
Running: node ../js/stepA_mal.js ../tests/perf3.mal
iters/s: 1585.3495967473173
```

**Comment by kanaka** [comment]
Tweeted: https://twitter.com/bus_kanaka/status/585187954999558144

I assume you'll open another PR for the perf test?

**Pull request merged**
