### PR TITLE
tests: Add test for unescaping "\\n" in step4

### PR DESCRIPTION
**Pull request by dubek**
Several implementations fail when unescaping "\\n" in their reader module because string-wide replacements of the two chars '\' and 'n' by a newline char will replace the last two chars.

A possible fix for those is of the following kind:

```
diff --git a/ruby/reader.rb b/ruby/reader.rb
index 1e60174..e47a687 100644
--- a/ruby/reader.rb
+++ b/ruby/reader.rb
@@ -23,7 +23,7 @@ def tokenize(str)
 end

 def parse_str(t) # trim and unescape
-    return t[1..-2].gsub(/\\"/, '"').gsub(/\\n/, "\n").gsub(/\\\\/, "\\")
+    return t[1..-2].gsub(/\\\\/, "\u029e").gsub(/\\"/, '"').gsub(/\\n/, "\n").gsub("\u029e", "\\")
 end

 def read_atom(rdr)
```

The special unicode char `\u029e` can be replaced by `\x01` or other special char that is unlikely to appear.

Fix needed in the following implementations:

- [x] awk
- [X] bash
- [X] basic
- [x] c
- [x] coffee
- [x] cs
- [x] chuck
- [x] common-lisp
- [x] crystal
- [x] d
- [x] dart
- [x] elixir
- [X] es6
- [x] factor
- [x] go
- [x] gst
- [x] guile
- [x] haxe
- [x] hy
- [x] io
- [X] js
- [x] julia
- [x] kotlin
- [x] lua
- [X] matlab
- [X] miniMAL
- [x] nim
- [x] objpascal
- [x] objc
- [x] perl
- [x] php
- [x] plpgsql
- [x] ps
- [x] powershell
- [x] python
- [x] r
- [x] racket
- [x] rexx
- [X] rpython
- [X] ruby
- [X] rust
- [x] scala
- [x] skew
- [x] swift3
- [x] ts
- [x] vb
- [x] vimscript

### CODE REVIEW

**Comment by dubek** [comment]
TBH a cleaner solution in Ruby would be:

```
def parse_str(t) # trim and unescape
  return t[1..-2].gsub(/\\./, { "\\\\" => "\\", "\\n" => "\n", "\\\"" => '"' })
end
```

**Comment by kanaka** [comment]
@dubek @wasamasa I made a branch from this on the main tree where we can work through the list as we have time. I've kicked it off by fixing bash, basic, es6, js, ruby, rust on that branch.

**Comment by kanaka** [comment]
I'll claim factor, matlab, miniMAL, and rpython next.

**Comment by kanaka** [comment]
I fixed matlab, miniMAL and rpython but I'm releasing factor. I think we're running a version 0.97 prior to support for unicode literals in strings. I tried updating to the latest nightly of factor but the "GENERIC#" word needed for defining "pr-str" no longer seems to work.

@jordanlewis any chance you're still around and might be able to give us a hint? Either how to encode a unicode/special ASCII character in the 0.97 version of factor or alternately how to fix the use of "GENERIC#" to work in the latest version of factor.

**Comment by wasamasa** [comment]
I'm claiming chuck, common-lisp, gst, guile and python.

**Comment by jordanlewis** [comment]
I'll try to take a look at this, it's been a while since I've played with factor tho 😁

**Comment by kanaka** [comment]
@jordanlewis cool. If it helps, here is the dockerfile change I used to get the latest factor nightly:

```patch
diff --git a/factor/Dockerfile b/factor/Dockerfile
index c213838..fd94e62 100644
--- a/factor/Dockerfile
+++ b/factor/Dockerfile
@@ -1,4 +1,4 @@
-FROM ubuntu:vivid
+FROM ubuntu:xenial
 MAINTAINER Joel Martin <github@martintribe.org>
 
 ##########################################################
@@ -24,8 +24,10 @@ WORKDIR /mal
 # Factor
 RUN apt-get -y install libgtkglext1
 RUN cd /usr/lib/x86_64-linux-gnu/ \
-    && curl -O http://downloads.factorcode.org/releases/0.97/factor-linux-x86-64-0.97.tar.gz \
-    && tar xvzf factor-linux-x86-64-0.97.tar.gz \
+    && curl -O http://downloads.factorcode.org/linux-x86-64/factor-linux-x86-64-2017-09-25-04-21.tar.gz \
+    && tar xvzf factor-linux-x86-64-2017-09-25-04-21.tar.gz \
     && ln -sf /usr/lib/x86_64-linux-gnu/factor/factor /usr/bin/factor \
-    && rm factor-linux-x86-64-0.97.tar.gz
+    && rm factor-linux-x86-64-2017-09-25-04-21.tar.gz
 
+RUN mkdir /.cache && \
+    chmod uog+rwx /.cache
```

BTW, any reasonable approach that fixes the original bug (string escaping) is fine too.

**Comment by kanaka** [comment]
Claiming cs, hy, nim, objpascal, ps, rpython, vb

**Comment by kanaka** [comment]
Claiming c, coffee, crystal, haxe, plpgsql and r.

**Comment by jordanlewis** [comment]
@bpollack can probably fix the Factor implementation more quickly than I can and he volunteered to take a look.

**Comment by kanaka** [comment]
Claiming lua, kotlin, objc, php, powershell, swift3, ts

**Comment by kanaka** [comment]
Claiming awk, d, dart.

**Comment by kanaka** [comment]
Just 10 left.

**Comment by dubek** [comment]
I'll take rexx, skew, vimscript, perl, go

**Comment by iqbalansari** [comment]
I can contribute fixes for io, racket and elixir

**Comment by wasamasa** [comment]
Um, for Racket it's a matter of `(with-input-from-string token read)`.  The whole string replacement business is not needed for nearly any Lisp (with the exception of CL where `\n` isn't interpreted as an embedded newline).

**Comment by iqbalansari** [comment]
Yeah figured that

**Comment by iqbalansari** [comment]
For python we can use ast the module and just do `ast.literal_eval` perhaps

**Comment by kanaka** [comment]
Looks like scala is the only unclaimed one. I'll claim that.

**Comment by kanaka** [comment]
@dubek I realized my commit messages have been contextless. I made a new personal branch fix-string-unescape2 with just my fixes but better commit messages. Feel free to rebase your pull using my fixed commits. Or if that's a pain, I can live with the personal shame... ;-)

**Comment by dubek** [comment]
@kanaka I rebased my two commits on `fix-string-unescape2`.

**Comment by dubek** [comment]
Together with #290 (racket, elixir, io, factor) we have everything covered. @kanaka it's up to you to arrange the commits/branches as you see fit and merge to master.

**Comment by kanaka** [comment]
All tests pass: https://travis-ci.org/kanaka/mal/builds/280849691

I've rebased all the commits together and merged them to master.

**Pull request closed without merging**
