### PR TITLE
Adds GNU awk implementaion

### PR DESCRIPTION
**Pull request by kariya-mitsuru**
I implemented all steps of Mal by GNU awk 4.1.1.

I checked that my implementation [passed all test cases](https://gist.github.com/kariya-mitsuru/cbe0a1bd515b288a8f0a) and self-hosted Mal implementation also [passed](https://gist.github.com/kariya-mitsuru/63cfd0169af4fa408f71) in my Docker environment.

### CODE REVIEW

**Comment by kanaka** [comment]
@kariya-mitsuru That's awesome!

Just a couple of minor things before I merge:

- Can you make the Makefile, README.md, and Dockerfile entry appear more alphabetical? Either by renaming the implementation directory to just awk (GNU awk sort of is the standard awk these days), or by leaving it as gawk, but by listing it right after Go in the Makefile, README and Dockerfile? I'm fine with either option.

- Update the count at the top of the README to 39 :-)

Once you've made those changes and I merge it, I usually have the developer tweet about their implementation and I retweet. Alternately, I can just tweet about it directly. Up to you.

**Comment by kariya-mitsuru** [comment]
I renamed the directory to awk, and the count to 39.

**Comment by kanaka** [comment]
Great! Merged.

Would you like to tweet the new implementation? If you do, please let me know your twitter handle. If you don't use twitter or would otherwise prefer not to, let me know that and I'll tweet it out myself.

Thanks for the new implementation and the other language cleanup/fixes you've done. How did you find the implementation process? Did you use the guide? If so, any feedback on areas that it worked well for you and where it could be improved?

Also, I hang out in #mal on freenode. It's generally pretty quiet, but a few other implementers hang out there for random mal/lisp chat.

**Comment by kariya-mitsuru** [comment]
I used the make-a-lisp process guide, that was very useful for me.

**Pull request merged**
