### PR TITLE
Mal implementation using Truffle/GraalVM

### PR DESCRIPTION
**Pull request by mmcgill**
Hi!

I've implemented Mal using the [Truffle Framework](https://github.com/oracle/graal/blob/master/truffle/README.md), to enable JIT compiling of Mal programs on GraalVM. I think it came out rather well...

```bash
   # Recursive Fibonacci on OpenJDK 11 with java mal
   $ ./run ../tests/fib.mal 30 10
   Times (in ms) for (fib 30) on java: [2062 1809 1814 1777 1772 1791 1725 1723 1786 1745]
   
   # Recursive Fibonacci on GraalVM with java-truffle mal
   $ ./run ../tests/fib.mal 30 10
   Times (in ms) for (fib 30) on java-truffle: [280 142 21 26 22 75 21 26 21 24]
   
   # That's an 82x speed-up! Just out of curiosity...
   # How does Clojure on OpenJDK 11? We'll even throw in a type hint.
   $ lein repl
   Clojure 1.10.0
   OpenJDK 64-Bit Server VM 11.0.7+10-post-Ubuntu-2ubuntu218.04
   user=> (defn fib [^long n] (if (= n 0) 1 (if (= n 1) 1 (+ (fib (- n 1)) (fib (- n 2))))))
   #'user/fib
   user=> (dotimes [i 5] (time (fib 30)))
   "Elapsed time: 32.0791 msecs"
   "Elapsed time: 31.7552 msecs"
   "Elapsed time: 31.5361 msecs"
   "Elapsed time: 31.4796 msecs"
   "Elapsed time: 31.4541 msecs"
```

All tests are passing (excepting the new quasiquote-related soft tests that were pushed while I was working on this), as are all self-hosted Mal tests on top of this implementation.

I've included a write-up with some simple benchmarks (subject to the same caveats as the _existing_ benchmarks).

~~I have _not_ attempted to dockerize anything yet, for no particular reason. I see that it's a requirement for inclusion, so I'll append a commit to this PR as soon as I get an opportunity. I thought I'd submit first, to see what you think :)~~

I've amended the PR with a Dockerfile, and confirmed that all Travis tests pass for me locally after building an image from it.

### CODE REVIEW

**Comment by mmcgill** [comment]
Merry Christmas, @kanaka! I hope you and yours are doing well :)

Any interest in a Truffle/GraalVM-based Mal, or should I close this PR? I'm sure you are supremely busy with family and work, please feel free to ignore this indefinitely :)

**Comment by kanaka** [comment]
Hi @mmcgill I'm finally getting around to doing some mal followup. In the meantime, I think that GraalVM has moved from docker hub to github's container registry. The exact version you were using doesn't seem to be available there. Here an updated Dockerfile that was at least able to build and start running the code (python needed for the test runner):

```
FROM ghcr.io/graalvm/graalvm-ce:java11-20.3.0

RUN microdnf install python3 && \
    ln -sf /usr/bin/python3 /usr/bin/python

RUN mkdir -p /mal
WORKDIR /mal
```

I've built that version of the image and pushed to docker hub (which means the Travis and Github Actions CI) should be able to process this now.

The next problem is that the tests start but crash:

```
$ make DOCKERIZE=1 test^java-truffle^step0
...
TEST: '!' -> ['',!]
Exception: OSError(5, 'Input/output error')
Output before exception:
Exception during HotSpotJVMCIRuntime initialization:
Exception in thread "main": java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: Could not find option TruffleFunctionInlining
	at org.graalvm.compiler.options.OptionsParser.parseOption(OptionsParser.java:132)
	at org.graalvm.compiler.options.OptionsParser.parseOptions(OptionsParser.java:74)
	at org.graalvm.compiler.hotspot.HotSpotGraalOptionValues.parseOptions(HotSpotGraalOptionValues.java:144)
	at org.graalvm.compiler.hotspot.HotSpotGraalOptionValues.initializeOptions(HotSpotGraalOptionValues.java:694)
	at org.graalvm.compiler.hotspot.HotSpotGraalOptionValues.defaultOptions(HotSpotGraalOptionValues.java:84)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.onSelection(HotSpotGraalCompilerFactory.java:79)
	at jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig.getCompilerFactory(HotSpotJVMCICompilerConfig.java:126)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:547)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.runtime(HotSpotJVMCIRuntime.java:174)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljdk_vm_ci_hotspot_HotSpotJVMCIRuntime_2_0002eruntime_00028_00029Ljdk_vm_ci_hotspot_HotSpotJVMCIRuntime_2(JNIJavaCallWrappers.java:0)
	at jdk.vm.ci.runtime.JVMCI.initializeRuntime(JVMCI.java)
	at jdk.vm.ci.runtime.JVMCI.getRuntime(JVMCI.java:65)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljdk_vm_ci_runtime_JVMCI_2_0002egetRuntime_00028_00029Ljdk_vm_ci_runtime_JVMCIRuntime_2(JNIJavaCallWrappers.java:0)
!

Makefile:410: recipe for target 'test^java-truffle^step0' failed
```

It seems like for step0 at least a few of the tests run successfully but other steps seems to exit before any output.

Anyways, if you willing to do a bit more debug, I would be happy to get this merged once it's ready.

**Comment by mmcgill** [comment]
Hi @kanaka ! I'll try to get my head back into this in the next week and see what needs freshening up.

**Comment by mmcgill** [comment]
@kanaka With this latest commit, on a fresh Ubuntu 20.04 VM, I get only soft failures for `make DOCKERIZE=1 test^java-truffle`.

**Comment by mmcgill** [comment]
I've rebased on master now, as well.

**Comment by kanaka** [comment]
@mmcgill okay, it's building and running for me now. A few more minor things before merging:
- the Dockerfile still needs python installed for the automated tests (and CI) to be able to run in a container. Please add this to the Dockerfile (I built and pushed a version of the dockerfile with this change already):
```
--- a/impls/java-truffle/Dockerfile
+++ b/impls/java-truffle/Dockerfile
@@ -1,4 +1,7 @@
 FROM ghcr.io/graalvm/graalvm-ce:21.1.0
 
+RUN microdnf install python3 && \
+    ln -sf /usr/bin/python3 /usr/bin/python
+
 RUN mkdir -p /mal
 WORKDIR /mal
```
- when I build in a container context, gradle seems to be creating a `?` directory where it caches things. I suspect that's because some environment variable isn't set maybe. If that's easy to cleanup (and not the expected behavior of gradle), the that would be great to get fixed up (probably setting an environment variable in the Dockerfile is what I would expect the most straightforwards fix to be).
- add it to the `IMPLS.yml` so that it will get picked up by the Github Actions automated CI script.
- update the top-level README: table, detail section, and the counts at the top. I'll let you make the call as to whether this is a new language or are different implementation in the same language (in terms of the counts).
- rebase the PR again (a couple other implementations got merged in the meantime and now conflict in `Makefile.impls`).

**Comment by mmcgill** [comment]
Thanks @kanaka!

Excellent guess RE: gradle, that's _exactly_ what was needed.

**Comment by kanaka** [comment]
Good news: the implementation is running and passing now in Github Actions CI.
Bad news: I did a more in depth review and identified a few issues that need to be resolved:
- There is a binary file checked in (`impls/java-truffle/gradle/wrapper/gradle-wrapper.jar`). If it's a resource from some other project it need to be either downloaded on demand (probably in the Dockerfile). Or if not, then it needs to be generated by either the Dockerfile or the build process (or maybe it already is and just got accidentally checed in). Make sure to remove it from the PR commit history so that it's not cloned with every mal repo clone/fetch.
- There are changes to `impls/lib` that impact every other implementation's perf testing. I think most implementations still pass but I do see that at least one of them that (the C64/cbm basic implementation) fails when running perf1.mal and perf3.mal. That implementation is severely memory constrained so it may simply be the increased amount of code in the perf changes. Or it could be something more subtle. The output from the perf test isn't checked right now so it doesn't cause the actual test run to fail so it's a manual check right now. I'm working on a way to get the output from all test runs in GH Actions and should be able to check this soon (I need to extract the numbers for benchmarking anyways). Also, I want to get error reporting from the perf part working at some point. If you want to get this merged sooner, maybe look at splitting out the lib changes into a place that only java-truffle picks up (and then we can look at merging it all together when I have the better idea of what's working and not).

**Comment by mmcgill** [comment]
> Good news: the implementation is running and passing now in Github Actions CI.

\o/

> Bad news [...]

Aw, shucks =)

> * There is a binary file checked in (`impls/java-truffle/gradle/wrapper/gradle-wrapper.jar`). If it's a resource from some other project it need to be either downloaded on demand (probably in the Dockerfile). Or if not, then it needs to be generated by either the Dockerfile or the build process (or maybe it already is and just got accidentally checed in). Make sure to remove it from the PR commit history so that it's not cloned with every mal repo clone/fetch.

I agree this feels weird, but according to the [Gradle documentation](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.wrapper.Wrapper.html) this JAR is produced specifically in inclusion in source control:

>The scripts generated by this task are intended to be committed to your version control system. This task also generates a small gradle-wrapper.jar bootstrap JAR file and properties file which should also be committed to your VCS. The scripts delegates to this JAR.

This appears to be [common practice](https://github.com/search?l=&q=filename%3Agradle-wrapper.jar&type=Code) (which is no justification on its own). I wasn't aware of this until just now, but the Gradle team provides a [Gradle Wrapper Validation](https://github.com/gradle/wrapper-validation-action) Github Action specifically for checking the SHA of the `gradle-wrapper.jar`  file against the checksums of official releases, to guard against malicious commits in the future.

If the Github Action sounds good to you, I can wire that up in the PR. If it's not worth the overhead for a single implementation, I'll strip it out, update the Dockerfile and amend the instructions for running locally to mention Gradle installation.

> * There are changes to `impls/lib` that impact every other implementation's perf testing. I think most implementations still pass but I do see that at least one of them that (the C64/cbm basic implementation) fails when running perf1.mal and perf3.mal. That implementation is severely memory constrained so it may simply be the increased amount of code in the perf changes. Or it could be something more subtle. The output from the perf test isn't checked right now so it doesn't cause the actual test run to fail so it's a manual check right now. I'm working on a way to get the output from all test runs in GH Actions and should be able to check this soon (I need to extract the numbers for benchmarking anyways). Also, I want to get error reporting from the perf part working at some point. If you want to get this merged sooner, maybe look at splitting out the lib changes into a place that only java-truffle picks up (and then we can look at merging it all together when I have the better idea of what's working and not).

Makes sense, and I should've been more careful here. I see now that the `^` reader macro (which I introduced into to files in lib/) is optional, and also that I accidentally pushed the removal of the warmup period in `run-fn-for`, which was completely unintentional.

I've rebased such that no existing files in `lib/` or `tests/` are modified.

**Comment by kanaka** [comment]
Weird, somehow I missed your most recent update.

I think I would prefer not to have it in the tree even if it is Gradle convention (they should just do the right thing and ship a sha256 hash and validate it when it's downloaded/invoked). I've update the Github Actions to store logs so I'll be able to more easily download and check when lib/perf changes happen.

If the Standard ML author responds quickly, then I'm planning to merge that one first. That may cause one more merge conflict that you'll need to rebase on (and update the counts one last time).

**Comment by mmcgill** [comment]
@kanaka I've stripped out the Graddle Wrapper, updated the Dockerfile to include a Gradle install, and rebased!

**Comment by kanaka** [comment]
I just merged it! Congrats. BTW, after comparing it again with the Java implementation, I decided that this is more than just a new runtime mode so I bumped the implementation count too. Do you have a twitter account? If so, want to tweet to announce it and post a link back here so I can retweet it? If not, I'm happy to tweet it out.

**Comment by mmcgill** [comment]
\o/

Thanks for all your feedback!

I don't have a Twitter account (that I use), so feel free to announce :)

**Comment by kanaka** [comment]
Announced: https://twitter.com/bus_kanaka/status/1400102029834477568

**Comment by kanaka** [comment]
Hey @mmcgill, relaying a message from @borkdude who tried to build native with native-image and ran into some issues: https://gist.github.com/borkdude/e0e12997ce3a7b09b44f15769add85a9 (tweet for reference: https://twitter.com/borkdude/status/1400149389654597632)

If either of you are interested in working this further, can one of you open a mal issue for tracking and discussion? Thanks.

**Comment by borkdude** [comment]
@kanaka Created an issue to track it. I might look into it. I've been looking into the Truffle framework a bit and curious about the optimizations. 

A bit of context: 

I'm the author of http://babashka.org, a fast native Clojure interpreter for scripting. It's built without any relation toTruffle, but it is compiled to native using GraalVM native-image, so it has the fast startup time (a few milliseconds).

It would be awesome to get babashka on par, performance-wise, with something like mal on truffle.

**Comment by kanaka** [comment]
@borkdude Oh I know! We use babashka here at work a fair bit. Thank you for your excellent work on that.

Also, @mmcgill is on my team at work. He will likely get back to you when he has some free cycles. If you haven't already figured out the problem in the meantime :smile:

**Pull request merged**
