### PR TITLE
Add Janet implementation

### PR DESCRIPTION
**Pull request by sogaiu**
This is an implementation of mal in [janet](https://janet-lang.org).

All tests pass in both direct and self-hosted modes:
```
make "test^janet"
make MAL_IMPL=janet "test^mal"
```

One notable feature is the use of peg parsing instead of regular expressions as Janet has built-in support for the former but not the latter.

Included in the PR is a Dockerfile I successfully tested in a VM.

### CODE REVIEW

**Comment by dubek** [comment]
Very nice @sogaiu and thank you for your contribution.

You'd also need to to add a commit modifying the main `README.md` - adding your implementation to the list and updating the counters above the list.

I read that Janet also has a compiler — does this impl use the compiler or the interpreter?

**Comment by sogaiu** [comment]
@dubek Thanks for taking a look and for the further instructions.  I will work on modifying the README.md.

Since submitting the PR, I've made further improvements (e.g. more consistent naming, arity and argument checking in core functions, added some tests for `janet-eval`, etc.).  These changes also pass the tests.

Should I update this PR with them?

Regarding your Janet query -- Janet has its own [abstract machine](https://janet-lang.org/docs/abstract_machine.html) so typically code is converted to bytecode before execution.  If you're familiar with how Clojure works (compiling to JVM bytecode before execution), perhaps it can be seen as somewhat similar.  Does that answer your question?

**Comment by dubek** [comment]
Thanks for the explanation.

Just keep updating this PR with the improvements.

**Comment by sogaiu** [comment]
Thanks for the guidance.

I've pushed the additional changes and updated the README.  I hope the counts are right :)

**Comment by kanaka** [comment]
@sogaiu Apologies for leaving this unanswered for moths. I took some time off but I am back now and following up on mal stuff. The code structure looks fine and it does pass all the tests and self-hosted tests. I've also pushed a build of the docker image to docker hub so you should be able to run Travis and Github Actions checks now.

However, I do notice that it seems to hang for the perf/benchmark test (the third/timed test):

```
$ make DOCKERIZE=1 perf^janet
----------------------------------------------
Performance test for janet:
Running: docker run -e STEP=stepA_mal -e MAL_IMPL=js -it --rm -u 1000 -v /data/joelm/personal/programming/mal-other/:/mal -w /mal/impls/janet kanaka/mal-test-janet ../janet/run ../tests/perf1.mal
Elapsed time: 0.0206861 msecs
Running: docker run -e STEP=stepA_mal -e MAL_IMPL=js -it --rm -u 1000 -v /data/joelm/personal/programming/mal-other/:/mal -w /mal/impls/janet kanaka/mal-test-janet ../janet/run ../tests/perf2.mal
Elapsed time: 0.0564344 msecs
Running: docker run -e STEP=stepA_mal -e MAL_IMPL=js -it --rm -u 1000 -v /data/joelm/personal/programming/mal-other/:/mal -w /mal/impls/janet kanaka/mal-test-janet ../janet/run ../tests/perf3.mal
*************** Should complete in about 10 seconds, but hangs here instead ******************
```

If you are able to fix this, and it passes CI, then I think this should be ready to merge.

**Comment by sogaiu** [comment]
@kanaka Thanks for taking a look!

I've modified `time-ms` and AFAICT it's working better locally via docker.

I didn't understand what you meant by:

> I've also pushed a build of the docker image to docker hub so you should be able to run Travis and Github Actions checks now.

Would you mind elaborating on that?  I'm not familiar with either Travis or Github Actions.  Is there some place I might look to learn more about what I should do?

**Comment by kanaka** [comment]
If you look at the bottom of this pull request page you'll see the automatic test results. These are currently split between two services: Github Actions for most things and Travis CI because it has broader support for OS X / XCode versions. If you rebase your changes onto master, you'll need to update `Makefile.impls` (instead of Makefile), and you can add janet to `IMPLS.yml` too (which is loaded by the Github Actions CI process). You can do the same for your fennel pull request.

Also, your janet and fennel implementations look ready to go (after you make the above changes). There was another implementation prior to yours so the counts in the README are now wrong. Just update the janet number. Updating fennel too will cause a merge conflict later so I'll do the fennel count for you after I merge them.

**Comment by sogaiu** [comment]
@kanaka Thanks for the explanation.

I've rebased and made adjustments.  Locally there don't appear to be any problems.

Looking at some of the CI results I see:
```
Status: Downloaded newer image for kanaka/mal-test-janet:latest
make: *** No targets specified and no makefile found.  Stop.
make: Entering directory '/mal/impls/janet'
make: Leaving directory '/mal/impls/janet'
Error: Process completed with exit code 2.
```

via https://github.com/kanaka/mal/pull/540/checks?check_run_id=2405433921

I wonder whether I have done something wrong.  Any hints?

**Comment by kanaka** [comment]
@sogaiu the problem is that the ci.sh scripts except a Makefile in each impl directory. I went ahead and fixed that and merged it after verifying everything else worked. Congrats! If you have a twitter announce, please announce it and post a link here and I will retweet. If you don't have an account I can just tweet out the implementation. Let me know.

**Comment by sogaiu** [comment]
@kanaka Thanks for your patience and efforts :)

I don't have a twitter account.

**Pull request merged**
