### PR TITLE
Works when ~/.mal-history does not exist

### PR DESCRIPTION
**Pull request by tebeka**

### CODE REVIEW

**Comment by kanaka** [comment]
@tebeka most of this pull is formatting/indent changes. Please clean up the pull so that it's just the fix and stays consistent with the existing formatting.

**Comment by tebeka** [comment]
@kanaka This is my vim setup which calls `gofmt`. This is the highly recommended way to indent Go code. If you still want - I'll try to revert the changes to be consistent with the old code.

Another option is to do one commit which is only running `gofmt` on the code and then my changes.

**Comment by kanaka** [comment]
Yes, please split it into two separate commits and I'll merge it. For the formatting commit, please do it across everything not just the readline.go file

**Comment by kanaka** [comment]
@tebeka sorry, for some reason github didn't notify me that you had updated the pull. Merged

**Comment by tebeka** [comment]
No worries, thanks!

**Pull request merged**
