### PR TITLE
Gnu smalltalk implementation

### PR DESCRIPTION
**Pull request by wasamasa**
Let me know what's missing.

### CODE REVIEW

**Comment by iqbalansari** [comment]
Damn I was working on this too :cry: :stuck_out_tongue:

**Comment by wasamasa** [comment]
@iqbalansari You know where to find me if you ever need to talk about what to implement next :D

**Comment by wasamasa** [comment]
@kanaka Announcement: http://emacsninja.com/posts/one-of-those-who-can-type.html

**Comment by kanaka** [comment]
Sorry, forgot to mention that I tweeted to the blog post a few days ago: https://twitter.com/bus_kanaka/status/886950911284846593

**Comment by wasamasa** [comment]
I see, thanks!

**Comment by zecke** [comment]
Have you considered defining/creating a package.xml to load the code?

**Comment by wasamasa** [comment]
I did, but it's a) verbose, b) requires spelling out a fixed set of files to load and c) isn't as simple as filling in a file name. 

On July 21, 2017 8:09:31 AM GMT+01:00, Holger Freyther <notifications@github.com> wrote:
>Have you considered defining/creating a package.xml to load the code?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/kanaka/mal/pull/264#issuecomment-316923056

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
