### PR TITLE
Add Factor implementation

### PR DESCRIPTION
**Pull request by jordanlewis**
This pull request adds a full mal implementation in [Factor](http://factorcode.org). It's complete except for collection metadata.

### CODE REVIEW

**Comment by kanaka** [comment]
Sweet! Factor is now the third concatenative language implementation of mal (after PostScript and Forth). I went ahead and updated the README count and noted that I have tested it with 0.97 of Factor.

Thanks, this is a really great addition. I was watching the network and you kind of came out of nowhere in the past few days. I was expecting Erlang or Elixir to get past the gate first. :-)

**Comment by kanaka** [comment]
@jordanlewis at this point the only thing left is for you to tweet about your implementation and I'll retweet it. Assuming you have a twitter account of course (otherwise I'll just do it). Also, some implementors hang out in #mal (freenode) for random discussion of things loosely related to mal.

**Comment by jordanlewis** [comment]
https://twitter.com/JordanALewis/status/583814762074664961

**Comment by jordanlewis** [comment]
Thanks for the project! That was a lot of fun. Implementing mal or any lisp really is a great way to learn a new language.

**Comment by kanaka** [comment]
Thanks, I'm glad you enjoyed it. How familiar were you with Factor before you started?

**Comment by jordanlewis** [comment]
I had never touched the language before I started!

**Pull request merged**
