### PR TITLE
C2

### PR DESCRIPTION
**Pull request by fungiblecog**
Hi Joel

Changes made as requested.

Regarding the below question: I mean that they behave like clojure's persistent collections in that they're immutable but making changes is cheap and performant because the new versions re-use part of the old versions. Anyway sounds like you're happy to accept improvements so I'll let you know when it's ready.

>Can you expand on what you mean by "persistent versions of hashmap and vector"? Do you mean improvements to the >efficiency of those structures within the c.2 implementation? I'm always happy to accept improvements to implementations even >after they have been merged (by the original author or by others).

Cheers
Duncan

### CODE REVIEW

**Comment by kanaka** [comment]
CI passed and code looks good! Merged. At this point, I would like to announce the implementation. If you have a twitter account, then please tweet it, link to your tweet here, and I will retweet it. If you don't then I'll tweet it myself. Congrats!

**Comment by kanaka** [comment]
BTW, in the future, the conventional way to update a pull request (so that all conversation and updates happen in the same place), is to force push the PR branch. Github PRs are the exception to the "never force push" rule.

For reference, previous discussion happened on earlier PRs: https://github.com/kanaka/mal/pull/517, https://github.com/kanaka/mal/pull/558

**Comment by fungiblecog** [comment]
I don't Tweet so feel free to do that.

I'm useless at git and even worse at github so every tip is very helpful, thanks.

**Comment by kanaka** [comment]
Tweeted: https://twitter.com/bus_kanaka/status/1392857006642434051

**Pull request merged**
