### PR TITLE
travis: add vimscript to matrix

### PR DESCRIPTION
**Pull request by dubek**

### CODE REVIEW

**Comment by kanaka** [comment]
Looks like it passed vimscript so I merged it in.

**Comment by kanaka** [comment]
Oh drat. I missed the fact that vimscript is now listed twice. BTW, the reason the vimscript test fails without NO_PERF=1 is due to some weird stdin/stdout permissions issue when running inside a docker container.

**Comment by kanaka** [comment]
I restarted the regular vimscript test since it failed I think due to me merging while it was in progress. Hopefully that will show the error.

**Comment by kanaka** [comment]
Okay, nm. Looks like it can't find the branch now that I've merged, so we'll just need to wait for the post merge test build: https://travis-ci.org/kanaka/mal/builds/97067125

**Comment by kanaka** [comment]
Unfortunately, the failure is just that it hangs: https://travis-ci.org/kanaka/mal/jobs/97067173

**Comment by dubek** [comment]
This stupid hack seems to solve the `/dev/stdout` problem:

```
diff --git a/Makefile b/Makefile
index 389c9d8..1748de5 100644
--- a/Makefile
+++ b/Makefile
@@ -264,11 +264,11 @@ $(IMPL_PERF):
          cd $(if $(filter mal,$(impl)),$(MAL_IMPL),$(impl)); \
          echo "Performance test for $(impl):"; \
          echo 'Running: $(call $(impl)_RUNSTEP,stepA,$(call $(impl)_STEP_TO_PROG,stepA),../tests/perf1.mal)'; \
-          $(call $(impl)_RUNSTEP,stepA,$(call $(impl)_STEP_TO_PROG,stepA),../tests/perf1.mal); \
+          $(call $(impl)_RUNSTEP,stepA,$(call $(impl)_STEP_TO_PROG,stepA),../tests/perf1.mal) | cat; \
          echo 'Running: $(call $(impl)_RUNSTEP,stepA,$(call $(impl)_STEP_TO_PROG,stepA),../tests/perf2.mal)'; \
-          $(call $(impl)_RUNSTEP,stepA,$(call $(impl)_STEP_TO_PROG,stepA),../tests/perf2.mal); \
+          $(call $(impl)_RUNSTEP,stepA,$(call $(impl)_STEP_TO_PROG,stepA),../tests/perf2.mal) | cat; \
          echo 'Running: $(call $(impl)_RUNSTEP,stepA,$(call $(impl)_STEP_TO_PROG,stepA),../tests/perf3.mal)'; \
-          $(call $(impl)_RUNSTEP,stepA,$(call $(impl)_STEP_TO_PROG,stepA),../tests/perf3.mal))
+          $(call $(impl)_RUNSTEP,stepA,$(call $(impl)_STEP_TO_PROG,stepA),../tests/perf3.mal) | cat)
 
 # REPL invocation rules
 # Allow repl^IMPL^STEP and repl^IMPL (which starts REPL of stepA)
```

Aside - I think the travis matrix declaration should be sorted, so vimscript should be after vb (that's what confused me). Maybe define them as one liners so we can easily sort in the editor:

```
matrix:
  include:
    - { env: IMPL=awk, services: [docker] }
    - { env: IMPL=bash, services: [docker] }
    - { env: IMPL=c, services: [docker] }

```

**Comment by dubek** [comment]
BTW the problem in Docker (no access to /dev/stdout /dev/stderr) is known: https://github.com/docker/docker/issues/6880 . The fix is merged and will appear in the next Docker release. Once that new Docker will be used by Travis we will be able to get rid of those ugly `| cat` pipes.

**Comment by kanaka** [comment]
I simplified and localized the fix by just adding it in vimscript_run.sh: https://github.com/kanaka/mal/commit/5f66fc069ea6be276f32c8250ee64aa6a8a63a8d

I also converted the .travis.yml matrix to single lines (good idea!).

Here is the travis build with those changes: https://travis-ci.org/kanaka/mal/builds/97455846

**Pull request merged**
