### PR TITLE
New test for closures

### PR DESCRIPTION
**Pull request by asarhaddon**
I have found this in an old mess of experimentations with ada.2.  Seems simple and worth testing.

### CODE REVIEW

**Comment by kanaka** [comment]
Yes, that's a really good test. It also broke nim which is unexpected.

**Comment by kanaka** [comment]
I fixed nim (4c7b1d6af04931e478e848f56c843c095aa018a6). It was just step3 and 4 that had the problem which was what I guessed given that later env handling and self-hosting worked fine.

**Comment by asarhaddon** [comment]
I have fixed ada.2 (disabling a misguided optimization attempt by a younger me :-1: ), added trivial changes to nim (that I was investigating too), and added a similar but more simple test.
The second test triggers an input/output error in.... zig.

**Comment by kanaka** [comment]
Oh, I never actually merged it. Merged now.

**Pull request merged**
