### PR TITLE
New SWI-prolog implementation

### PR DESCRIPTION
**Pull request by asarhaddon**
with, in stepA_mal.mal, a new way to pass all test and break
self-hosting nevertheless.

### CODE REVIEW

**Comment by kanaka** [comment]
I built and pushed a docker image. I tested locally and everything passes. Reviewed the code and looks good to me. The Travis test mode currently fails because it expects at least a stub Makefile in the implementation directory. If you add that (assuming it passes Travis) I'll merge after that.

**Comment by asarhaddon** [comment]
The run_argv_test.sh freezes in Travis but passes locally. I have no idea how to fix that.

**Comment by kanaka** [comment]
Interesting, last time I checked it locally it was passing. Now it's broken locally for me. To debug, I tried running it directly inside the docker container. It appears to be stuck in an infinite loop:

```shell
$ make DOCKERIZE=1 docker-shell^prolog
/mal/impls/prolog$ swipl ../prolog/step6_file.pl ../tests/print_argv.mal aaa bbb ccc
("aaa" "bbb" "ccc")
("aaa" "bbb" "ccc")
("aaa" "bbb" "ccc")
("aaa" "bbb" "ccc")
("aaa" "bbb" "ccc")
("aaa" "bbb" "ccc")
...
```

If I check out the previous version (d696b70ee2256e7325a75db75e4f6227c33ddc9b) it doesn't hang.

**Comment by asarhaddon** [comment]
Hello. This banch seems ready for merge. Am I missing something?

**Comment by kanaka** [comment]
@asarhaddon Sorry for the really long delay and for silently disappearing for the past half year. Looking back on it, I was probably experiencing some degree of burnout and only able to think about the bare essentials (day job and family). I'm back now (hopefully). I rebuilt the image and retested your implementation and everything checks out. Merged.

**Comment by kanaka** [comment]
@asarhaddon I want to announce the Prolog implementation and new count on Twitter. If you have an twitter account, then you should tweet it and I'll retweet yours. Otherwise I'll just tweet it myself. If you don't have a twitter account, do you want me to credit you in some way? Let me know.

**Comment by asarhaddon** [comment]
Neglecting MAL from times to times reveals a good sense of priorities :-).
I have no twitter account.  For credits, I am fine with this pseudonym or my real name as you see fit.

**Comment by kanaka** [comment]
@asarhaddon Done: https://twitter.com/bus_kanaka/status/1385735586162483202

**Pull request merged**
