### PR TITLE
Zig implementation

### PR DESCRIPTION
**Pull request by rjtobin**
This is preliminary Zig implementation. There are a number of things I'd love to work on further, in particular performance and memory management, but I wanted to push it before the winter holidays. Fair warning that I used this as a project to get familiar with Zig, so there is probably a lot that can be improved upon here (and hopefully I'll be able to make some of those improvements in the coming months).

Seems to pass Docker tests locally, but no doubt will take a few rounds to satisfy the CI tests.

### CODE REVIEW

**Comment by kanaka** [comment]
I've built and pushed a zig docker images to docker hub.

When I try and use it to build and test I get the following error:

```
$ make DOCKERIZE=1 test^zig
docker run -it --rm -u 1000 -v PATH/mal/:/mal -w /mal/zig kanaka/mal-test-zig make step0_repl
nzig2 build #step0_repl.zig
Unable to hash /mal/zig/src/main.zig: file not found
The following command exited with error code 1:
/usr/local/bin/zig-linux-x86_64-0.5.0/zig build-exe /mal/zig/src/main.zig --cache-dir /mal/zig/zig-cache --name zig --cache on 

Build failed. The following command failed:
/mal/zig/zig-cache/o/ZEwrx-xKef1WcRElcsYvppIqSPeIj00W5N0AC1CA6ewwS8m50vTL-fvg5gj1h0ND/build /usr/local/bin/zig-linux-x86_64-0.5.0/zig /mal/zig /mal/zig/zig-cache
Makefile:10: recipe for target 'step0_repl' failed
make: *** [step0_repl] Error 1
Makefile:384: recipe for target 'zig/step0_repl' failed
make: *** [zig/step0_repl] Error 2

```

I think there may be some build steps/prerequisite deps that need to be built in the zig/Makefile

**Comment by rjtobin** [comment]
Looks like the Zig build script wasn't committed. It's added now. I tested in a fresh checkout, and it seems to pass for me now. Can you verify?

I see a few things I'd like to tidy. Am happy to make a separate PR for those, or I can make them directly into this PR later in the weekend.

**Comment by rjtobin** [comment]
I pushed my changes. I had to change the Dockerfile, so you'll need to remake the image on docker hub. Sorry about that! It seems to work if I point it to my docker hub image (tobinrj/mal-test-zig), so I think we should be good this time.

**Comment by kanaka** [comment]
I've pushed out a new build of the docker image. I did a brief review of the code and noticed that step2 is using env.zig. It's preferable to implement a very simple non-hierarchical dictionary in step2 than using the full env implementation.

**Comment by rjtobin** [comment]
> I've pushed out a new build of the docker image. I did a brief review of the code and noticed that step2 is using env.zig. It's preferable to implement a very simple non-hierarchical dictionary in step2 than using the full env implementation.

Got it, definitely a mistake. I've pushed a new commit that replaces Env in step2 with a hashmap.

**Comment by kanaka** [comment]
@rjtobin Okay, next steps are to add it to `.travis.yml` to get Travis testing it and add it to the README.

**Comment by rjtobin** [comment]
Ok, modified the README and travis config file. Looks like the Zig tests passed, but somehow some of the other Travis tests got cancelled before they could complete.

**Comment by kanaka** [comment]
I temporarily cancel some of the sub-tests so that it would get to zig faster. I re-activated them after. Everything looks good. Merged.

Only thing left is to announce it. If you have a twitter account then please let the world know and post a link to your tweet here and I'll retweet it.

Thanks for the new implementation! Now we just need implementations starting with 'q', 'u', and 'x'. :-)

**Pull request merged**
