### PR TITLE
Clarify "rest" builtin in guide.md

### PR DESCRIPTION
**Pull request by epylar**

### CODE REVIEW

**Comment by epylar** [comment]
My bad, need to change wording.

**Comment by epylar** [comment]
Done.

**Comment by kanaka** [comment]
@epylar sorry for the slow reply. Last week I was heads down finishing my PhD dissertation. That's now done (yay!!!) so I've had a chance to look at this now. Clarification looks good. Thanks.

**Comment by gblewis1** [comment]
@kanaka Awesome! May I ask what your dissertation is about?

**Comment by epylar** [comment]
@kanaka Awesome! May I ask what your dissertation was about?

**Comment by kanaka** [comment]
@epylar The title is "Using Property-Based Testing, Weighted Grammar-Based Generators, and a Consensus Oracle to Test Browser Rendering Engines and to Reproduce Minimized Versions of Existing Test Cases"

It had three interrelated parts/modules:
1) Extending QuickCheck style property-based testing (PBT) to use EBNF grammars for the input properties and to have weighted probabilities attached to the input generators, and some automatic algorithms for adjusting those weights to accomplish coverage or reproduction goals: https://github.com/kanaka/instacheck
2) Translating W3C specification data into EBNF grammars: https://github.com/kanaka/html5-css3-ebnf
3) Using those two other module with a multiple browser consensus oracle to do automated browser render testing: https://github.com/kanaka/bartender Here is data published from 150 hours of Bartender tests: https://kanaka.github.io/bartender

**Comment by epylar** [comment]
@kanaka Seems like Clojure is a pretty productive language (I notice all of these are in Clojure). I'm almost done with my Rust Mal implementation and I'll be doing Clojure next.. should be interesting.

**Comment by kanaka** [comment]
@epylar there are a number of reasons I chose Clojure including: lots of excellent Clojure libraries like test.check, test.chuck, instaparse, reagent, Hickory, Oz, differ, specter, ring, etc; access to the entire Java ecosystem (without the boilerplate); fast at runtime due to the JVM; concise code; Lisp; etc.

**Pull request merged**
