### PR TITLE
Portable implementation in Common LISP

### PR DESCRIPTION
**Pull request by iqbalansari**
Hi,

This a (hopefully) portable implementation of MAL in Common LISP which would replace the current CLISP implementation, there are few pending issues

- [x] The MAL hashtable implementation is not portable yet (does not work with atleast GNU CLISP, ECL and ABCL)
- [x] The helper functions `getenv` and `command-line-args` in utils.lisp can be more portable
- [x] Support for creating executables for different implementations
- [x] Implementations supported
    - [x] SBCL
    - [x] CCL
    - [x] Allegro
    - [x] CLISP
    - [x] CMUCL
    - [x] ECL
    - [x] ABCL

Thanks

### CODE REVIEW

**Comment by kanaka** [comment]
Looking good so far. I built a docker image based on your current Dockerfile and pushed it so you'll be able to use it with Travis testing.

**Comment by kanaka** [comment]
Tests failed. Looks like maybe a temp file issue with quicklisp? https://travis-ci.org/kanaka/mal/jobs/177085545

**Comment by iqbalansari** [comment]
Yeah seems to be a permissions issue. Will try pushing a fix today.

**Comment by iqbalansari** [comment]
Hi, I have pushed a fix for the permissions error. Could you please update the docker image based on the Dockerfile [here](https://github.com/iqbalansari/mal/blob/542e99704899f6d7a5ec57105b33396f2ea72805/common-lisp/Dockerfile)

**Comment by kanaka** [comment]
Just pushed an update and restarted. The tests pass. Merged.

**Comment by kanaka** [comment]
Tweeted: https://twitter.com/bus_kanaka/status/800745120794427392

**Comment by kanaka** [comment]
Thanks pushing through and getting this working. I'm sure it was tedious :-)

**Comment by iqbalansari** [comment]
Thanks a lot! Learned a lot while during this, so the pleasure is mine :smile:

**Comment by kanaka** [comment]
Good to hear. Also, you are now a member of a very small and elite group of people that know how to create CL applications that support multiple versions of Common Lisp. Not sure there is much demand for such skills, but if I hear of such a need, I'll be sure to point them your way :-)

**Pull request merged**
