### PR TITLE
Update Elixir syntax & version to work with v1.5.x

### PR DESCRIPTION
**Pull request by amorphid**
The v1.0 syntax was deprecated, and threw a lot of deprecation warnings.  I fixed the warnings, and bumped the Elixir version to v1.5.  I shouldn't have introduced any bugs, but there aren't any tests, so hard to know for sure.

### CODE REVIEW

**Comment by kanaka** [comment]
Tests are run like this:

    make 'test^elixir'

Or run them using the mal docker image for elixir like this:

    make DOCKERIZE=1 'test^elixir'

Currently the tests are failing on Travis: https://travis-ci.org/kanaka/mal/jobs/274729638

Seems like the erlang version in the docker image is too old.

Let me see if I can figure out how to update the docker image to a later version of erlang.

**Comment by amorphid** [comment]
Gotcha.  If you like, I'll take a look later today.  I'd be interested in investigating anyway.

**Comment by kanaka** [comment]
Okay, I'll hold off. I suspect that updating the Dockerfile to ubuntu:xenial and removing the erlang-solutions install would probably work (i.e. just install the ubuntu elixir package).

**Comment by amorphid** [comment]
Yes, the kanaka/mal-test-elixir image needs to be updated.  I don't believe that's something I can do for you.  I did test the Elixir install instructions on debian/xenial64 using Vagrant & Virtualbox, and they worked fine.  So update it or don't!  Either way, cool little project :)  Cheers.

**Comment by kanaka** [comment]
@amorphid I went with a slightly simplified Dockerfile and it seems to work fine. Here is the diff from what you have (I also removed some extra spaces that slipped in):

```patch
--- elixir/Dockerfile.orig	2017-09-13 13:27:45.458331919 -0500
+++ elixir/Dockerfile	2017-09-13 13:28:02.850586119 -0500
@@ -1,4 +1,4 @@
-  FROM ubuntu:xenial
+FROM ubuntu:xenial
 MAINTAINER Joel Martin <github@martintribe.org>
 
 ##########################################################
@@ -22,7 +22,4 @@ WORKDIR /mal
 ##########################################################
 
 # Elixir
-RUN wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && dpkg -i erlang-solutions_1.0_all.deb
-RUN apt-get -y update
-RUN apt-get install -y esl-erlang
-RUN apt-get install -y elixir
+RUN apt-get -y install elixir
```

I've built a docker image based on my simplified Dockerfile and have pushed it to docker hub. Would you mind updating your Dockerfile in the pull request? I'll merged after that.

**Comment by amorphid** [comment]
Howdy.  So I think the problem is there's an intermediate step missing.  On this line here... 
 
https://travis-ci.org/kanaka/mal/jobs/275189767#L563

...Travis is pulling down the latest kanaka/mal-test-elixir image.  I don't think that image is built from the Dockerfile I submitted.  A container built from the Dockerfile I submitted works fine when I run it locally.  I'm not a Docker wizard, so am I missing something?

**Comment by kanaka** [comment]
@amorphid you're right, there was still a mismatch between your code changes and the docker image I pushed. I've pushed a build based on your Dockerfile and the test now passes. Merged! Thanks for following this all the way through.

**Comment by amorphid** [comment]
Glad to help!  I'm just glad not I'm not totes crazy :)

**Pull request merged**
