### PR TITLE
Ada2

### PR DESCRIPTION
**Pull request by asarhaddon**
I hope that review will be easyer with a pull request.
Please warn me of any change by email, as I do not intend to connect to github on a regular basis.
Thanks.

### CODE REVIEW

**Comment by kanaka** [comment]
@asarhaddon sorry for the slow reply. I haven't been ignoring this, I've just been sick and have had a bunch of other stuff going on.

The two test changes should be separate pull requests. Those changes broke other implementations so those will need to be fixed independently of this (https://travis-ci.org/kanaka/mal/builds/166498100) and that sometimes depends on availability of the original implementors before that happens.

Hopefully I'll be able to take a look at your implementation again soon.

**Comment by asarhaddon** [comment]
Joel Martin:
> @asarhaddon sorry for the slow reply. I haven't been ignoring this, I've just been sick and have had a bunch of other stuff going on.
> 
> The two test changes should be separate pull requests. Those changes broke other implementations so those will need to be fixed independently of this (https://travis-ci.org/kanaka/mal/builds/166498100) and that sometimes depends on availability of the original implementors before that happens.
> 
> Hopefully I'll be able to take a look at your implementation again soon.

I am quite busy for a few weeks, so a slight delay before playing with
MAL again is a very good think from my point of view :-)

Thanks for the status update anyway.

I hope that you are recovering well.

**Comment by kanaka** [comment]
@asarhaddon I'm closing this ticket since it's been open for a while with no updates. If you do get around to cleaning up the commits, please push the updates to this pull request and add a comment indicating you want me to re-open and consider it again.

Some other comments on the change:
- While most implementations of the eval function run it within the top-level lexical environment (i.e. repl_env) there is no strict requirement for this. So that test should either be dropped or moved to the optional section of the tests.
- There is a trivial Makefile conflict that will need to addressed (the list of IMPLS has changed in the meantime).
- Can you you give a brief blurb about how this differs from the existing Ada implementation? My rule-of-thumb for including multiple implementations is that they must show some fairly significant difference in approach. So if I do merge this I would like to include brief text in the top-level README about the difference.

Thanks!

**Comment by asarhaddon** [comment]
Hello.
I have improved the Ada2 implementation in so many ways that you will probably want to review it again before inclusion, but the overall design is unchanged so this should be easy. The first paragraph of ada2/README summarizes the differences with the initial Ada implementation.

**Comment by kanaka** [comment]
@asarhaddon I've re-opened the issue. I've done some initial review of the code and it looks good overall. The README is very helpful.

I've run into a compilation failure however:

```
gnatmake step1_read_print.adb -o step1_read_print -cargs -gnat2012  -O2 -gnatnp -largs  -lreadline
gcc-4.9 -c -gnat2012 -O2 -gnatnp step1_read_print.adb
types-atoms.ads:25:24: "Ref" is undefined (more references follow)
types-atoms.ads:25:24: possible misspelling of "Rec"
gnatmake: "step1_read_print.adb" compilation error
Makefile:60: recipe for target 'step1_read_print' failed
```

I think the main other change I would like to see is that the implementation directory be renamed to "ada.2". This will help disambiguate that this is a second implementation in Ada rather than an implementation in "Ada 2". I have pushed an image to docker hub named "ada.2" (copy of the "ada" image) so once you rename the implementation, you should be able to add this implementation to the .travis.yml so that we can get it building/testing in Travis.

**Comment by kanaka** [comment]
Also, please rebase the commit history to remove/cleanup the merge points and the tests changes (first two commits) that are already upstream in the repo.

**Comment by asarhaddon** [comment]
Hello.

The build failure is probably caused by gnat-4.9, which has only has limited support for Ada2012 features. I have added explicit prefixes, but the whole invariant may be removed easily if necessary.

I have rebased the changes into a new branch ada.2 of my repository, but I am not fluent enough with git(hub) to push such a rebase to a distant repository. It may be more simple to create a new pull request from the new ada.2 branch, if this fits your needs.

By the way, I have an unrelated suggestion for the process (step4). The "do" special could become a built-in function in core, very similar to the "first" built-in function. This would slightly simplify one of the first steps. Of course, "do" would not benefit from tail call optimization anymore.

**Comment by kanaka** [comment]
I created and pushed a new version of the `kanaka/mal-test-ada.2` image to docker hub that is built with gnat-8. I used the following Dockerfile. Please add this to your repo at ada.2/Dockerfile.

```dockerfile
FROM ubuntu:18.04
MAINTAINER Joel Martin <github@martintribe.org>

##########################################################
# General requirements for testing or common across many
# implementations
##########################################################

RUN apt-get -y update

# Required for running tests
RUN apt-get -y install make python

# Some typical implementation and test requirements
RUN apt-get -y install curl libreadline-dev libedit-dev

RUN mkdir -p /mal
WORKDIR /mal

##########################################################
# Specific implementation requirements
##########################################################

# GNU Ada compiler
RUN apt-get -y install gnat-8
```

I'm fine with whichever route you want to take. Creating a new PR for ada.2 is fine with me. Once you create the PR it should trigger Travis to automatically test the build.

**Comment by kanaka** [comment]
Hi @asarhaddon. We're you going to send a PR for your ada.2 branch?

**Pull request closed without merging**
