### PR TITLE
mal implementation in Elm 0.18 ported to Elm 0.19

### PR DESCRIPTION
**Pull request by Pancakem**

### CODE REVIEW

**Comment by kanaka** [comment]
@Pancakem did you intend to close this? Seems like there are some good improvements here. Perhaps you just closed it to fix the build/Travis issue?

**Comment by Pancakem** [comment]
> @Pancakem did you intend to close this? Seems like there are some good improvements here. Perhaps you just closed it to fix the build/Travis issue?

Yes, I closed it to fix issues.

**Comment by kanaka** [comment]
Hi @Pancakem, Is this ready for merging? The Travis tests won't pass until the upstream docker hub image is updated. If it's passing for you locally, then I'll update the image so that Travis will pass too.

**Comment by Pancakem** [comment]
> Hi @Pancakem, Is this ready for merging? The Travis tests won't pass until the upstream docker hub image is updated. If it's passing for you locally, then I'll update the image so that Travis will pass too.

Hello @kanaka. Finally got around to finishing this. Local tests pass.

**Comment by kanaka** [comment]
@Pancakem sorry for the slow reply. I just had a chance to look at this. I forgot that elm uses npm for installation so it doesn't actually require me to update the Docker image upstream. Looks like their are a few macro failures and the perf3 micro-benchmark which is timing out:

The build is at: https://travis-ci.org/github/kanaka/mal/jobs/684724080. Lines 1293-1314 show the macro failures and the timing out test is at line 3321

Once those issues are fixed then I will merge it.

**Comment by Pancakem** [comment]
> @Pancakem sorry for the slow reply. I just had a chance to look at this. I forgot that elm uses npm for installation so it doesn't actually require me to update the Docker image upstream. Looks like their are a few macro failures and the perf3 micro-benchmark which is timing out:
> 
> The build is at: https://travis-ci.org/github/kanaka/mal/jobs/684724080. Lines 1293-1314 show the macro failures and the timing out test is at line 3321
> 
> Once those issues are fixed then I will merge it.

Thank you. I will fix that.

**Comment by kanaka** [comment]
Hi @Pancakem I know it's been a long time but I was wondering if you've had any chance to look at this. The current elm implementation of mal in elm (0.18) has been broken for a while because the elm-0.18 Linux package was removed quite a while ago. If I can't find somebody to resurrect the elm build/impl, then I'll probably need to remove it from mal.

@c0deaddict since you are the original creator of the elm mal implementation, any interest in getting it working again with elm 0.19 if @Pancakem isn't able to?

**Comment by c0deaddict** [comment]
I can have a look at it, if @Pancakem doesn't have the time. That probably won't be sooner than February next year, a busy period is coming up and I'm currently focusing on getting the Advent of Code completed :smile:

**Comment by asarhaddon** [comment]
Hello @Pancakem and @c0deaddict.
I am sorry but I have duplicated your efforts in #608.
Because of the variable renamings, there is a lot of noise in the diff, and merging is a pain.
Please tell me if I have forgotten something important, apply an automatic formatter to my last commit and send me the diff, or more generally improve the merge in any way.
Especially, someone with experience in this language would probably find a way to move the sources to 'src/', name them with a lowercase letter and/or name the module in each step file 'Main'. The tricks I have used in order to build are most probably more complex than necessary, especially the ugly test in bootstrap.js special-casing step A.
All tests pass on my machine, so maybe we should update the Docker image, merge now and postpone the style issues.

**Comment by c0deaddict** [comment]
Nice work @asarhaddon ! I glanced over your changes and they look good to me. I do have to admit that I haven't read or written Elm code for a few years, so i'm a bit rusty. I agree with you that the best way forward is to get your PR merged. The styling issues can be fixed later on, as a further improvement.

**Comment by kanaka** [comment]
Super delayed, but elm is now at 0.19 with merging of changes from https://github.com/kanaka/mal/pull/608

**Pull request closed without merging**
