### PR TITLE
Add Standard ML implementation

### PR DESCRIPTION
**Pull request by fabjan**
The implementation passes all the tests and self-hosting works. The Dockerfile and Travis CI scripts worked when I tested locally.

(I did run into issues with the root Makefile on my Mac when running with DOCKERIZED=1: $(MAKE) in the makefile on my Mac expands to `/Library/Developer/CommandLineTools/usr/bin/make` in get_build_command, and that is not an executable Ubuntu in Docker liked.)

I have tried to organize the code according to the steps in the guide, but to keep the implementation idiomatic not all functions are named as in the guide (e.g. READ, EVAL, PRINT look like datatype constructors in SML, so they are read, eval, print instead). I'm not an SML professional, so I can't swear everything is idiomatic. E.g. I think the project is small enough to not warrant organizing in Structures.

Also, I got stuck with TCO for a while (my implementation itself is not using all tail calls in eval) so moved on and did not get back yet to it, hence step 5 does not exist.

### CODE REVIEW

**Comment by fabjan** [comment]
From the CI fail:

```
docker: Error response from daemon: pull access denied for kanaka/mal-test-sml, repository does not exist or may require 'docker login'.
236
```

... hmm, I maybe misunderstood how the Dockerfile is used. The build script does not appear to build and tag it for use later, so is that something someone does manually first? Maybe CI is typically done after merge in this repo?

**Comment by dubek** [comment]
Thanks for your SML contribution @fabjan .

You're doing nothing wrong with docker; we'll have to wait until @kanaka (who manages this project and the Docker repository) will use your Dockerfile to generate the new `kanaka/mal-test-sml` image. But I haven't heard from him here for a while, I hope he's OK (I don't have a lot of time to invest in Mal myself either).

If SML has built-in TCO, then you don't need to implement one. For example, in the OCaml implementation, `step5_tco.ml` is simply a symbolic link to step4, because step4 already utilizes the OCaml compiler's TCO.

**Comment by fabjan** [comment]
Yeah I saw when I created the PR that there were some implementations from a few months ago not yet merged. But there is of course no rush for something like this.

Yeah SML does tail call optimization, but I don't think my code is doing all tail calls so it will blow the stack evaluating deep recursion. I'll compare for the OCaml to see if I can find some hints. Although perhaps a more mal-implementation-idiomatic way to do it would be to mutate references to env and ast in a loop instead of recursively calling eval. It will be less idiomatic SML but it might better illustrate the optimization step.

**Comment by kanaka** [comment]
@fabjan I built and pushed out a docker image for sml and it passed when restarted it in Travis. I'm working on reviewing some of the earlier new implementation submissions that languished while I've been incommunicado. Hopefully won't be too long before I'm able to review this and merge it. In the meantime, can you add this to the Github actions definition file (`.github/workflows/main.yml`)?

**Comment by fabjan** [comment]
@kanaka welcome back!

I rebased my branch on master and force pushed, assuming nobody else is depending on it. If you prefer I can also squash the commits.

Since I was updating the CI anyway I updated the Dockerfile to support all `sml_MODE` options and added them to CI, like e.g. the Scheme implementation works. I also noticed a portability issue that I fixed (with MLton in dockerized ubuntu, `time-ms` had overflow errors because `Int` was 32 bit so I switched to `LargeInt` which had some knock-on effect in Moscow ML). I reran all the tests for all modes, dockerized on my MacBook, and they pass. It unfortunately means a new image needs to be built.

**Comment by kanaka** [comment]
I built a new docker image and pushed it. I've also been doing some refactoring of the CI stuff to make it more flexible so I can launch individual implementations from the Github Actions web UI. Those changes have caused some conflicts with your PR. Can you rebase again? I've also submitted an open source exception to docker hub although I haven't heard back yet. If they don't grant that waiver, then I'll make some more tweaks to try and reduce the number of tests that run when people create pull requests for new languages.

I've done a pass through all the pending PRs. There are two implementations in front of yours in the line that are basically ready (janet and fennel). Once those are merged (and after you rebase) then I should be able to merge sml soon after that.

**Comment by fabjan** [comment]
@kanaka thanks for the update, no sweat.

**Comment by kanaka** [comment]
Janet and Fennel are in now, but there is one more that was PR'd before SML that turns out is basically ready except for a few final tweaks by the author (an implementation in Truffle). SML should be next up after that. It will probably happen in the next day or so. Stand by.

**Comment by kanaka** [comment]
@fabjan Okay, I had some cycles today. Looks like the Java/Truffle implementation may still be a few days out. Let's go ahead and get SML merged. If you'll rebase again (to resolve the `Makefile.impls` conflict) and then update the counts based on the current README upstream, I'll merge your implementation next.

**Comment by fabjan** [comment]
@kanaka No worries, I rebased and updated the readme. I added one language (SML), one implementation (mine), and three runtime modes (Poly/ML, MLton, Moscow ML). I hope that was the right interpretation of those counts.

I also updated the README table to include my SML implementation and some info about it like for the others. I hope that is the way, unless you prefer to fill those in later?

**Comment by kanaka** [comment]
@fabjan Everything looks good including the counts and README updates. Merged! Congrats. If you have a twitter account and would like to announce it, please do that and link back here and I will retweet it. If not, then I can just tweet it myself to announce it.

**Comment by fabjan** [comment]
@kanaka Thanks, and thanks a lot for making MAL! It was a great couple of weeks and the way you laid it out (even if it was not a perfect fit for a functional solution) helped me get unstuck having made a few attempts on my own before at making a simple lisp.

I don't really use twitter aside from the automated Playstation integration for sharing screenshots and stuff, so you can just tweet if that's how you announce new implementations :)

**Comment by kanaka** [comment]
I tweeted it but then forgot to post a link back here: https://twitter.com/bus_kanaka/status/1389339175313453060

**Pull request merged**
