### PR TITLE
Add Dart implementation

### PR DESCRIPTION
**Pull request by hterkelsen**
I've writted a Dart implementation of Mal. It passes all the tests.

Let me know if there's anything else I need to do to get this merged. Thanks!

### CODE REVIEW

**Comment by hterkelsen** [comment]
I added a Dockerfile for Travis

**Comment by dubek** [comment]
Thank you @hterkelsen ; looks good! Once @kanaka builds and pushes the docker image, we will be able to try this PR in Travis again.

**Comment by kanaka** [comment]
Okay, I pushed a build of the docker image.

I restarted the test in travis (https://travis-ci.org/kanaka/mal/jobs/175572490) but it's still failing because Travis attempts to do `make` in the implementation directory. So you need a stub Makefile. Here is a stub Makefile (that also includes the stats targets for size comparisons):

```Make
all: 
        @true

SOURCES_BASE = types.dart reader.dart printer.dart
SOURCES_LISP = env.dart core.dart stepA_mal.dart
SOURCES = $(SOURCES_BASE) $(SOURCES_LISP)

.PHONY: stats tests $(TESTS)

stats: $(SOURCES)
        @wc $^
        @printf "%5s %5s %5s %s\n" `grep -E "^[[:space:]]*//|^[[:space:]]*$$" $^ | wc` "[comments/blanks]"
stats-lisp: $(SOURCES_LISP)
        @wc $^
        @printf "%5s %5s %5s %s\n" `grep -E "^[[:space:]]*//|^[[:space:]]*$$" $^ | wc` "[comments/blanks]"
```

Other than that, everything looks good. I also checked that self-hosted tests also pass and they do.

**Comment by hterkelsen** [comment]
Thanks, @kanaka. I added `dart/Makefile` so hopefully it'll pass on travis now.

**Comment by kanaka** [comment]
I cancelled the other implementations and restarted Dart: https://travis-ci.org/kanaka/mal/jobs/175857107

It passed, so merged!

The only remaining task is for somebody to tweet it an announcement. If you want to do that, point me at your twitter handle and I'll retweet. Otherwise, I can just do it.

**Comment by hterkelsen** [comment]
Thanks, I tweeted it out here if you want to retweet: https://twitter.com/harryterkelsen/status/798281889588998145

**Comment by kanaka** [comment]
@hterkelsen also, some of the mal implementors (and others) hang out at #mal on freenode.

**Pull request merged**
