### PR TITLE
q impl

### PR DESCRIPTION
**Pull request by alimpfard**
Still has some work left, but self-hosting does work now.

- [x] unordered hashmap comparison (this is an unused optional, so I'm gonna pass on implementing it)
- [x] stepA optionals
- [x] a docker thingy (somehow...)
- [x] anything else that pops up

### CODE REVIEW

**Comment by alimpfard** [comment]
As for perf:
```
----------------------------------------------
Performance test for q:
Running: env STEP=stepA_mal MAL_IMPL=js ../q/run ../tests/perf1.mal
KDB+ 3.6 2019.04.02 Copyright (C) 1993-2019 Kx Systems
l32/ 8()core 15892MB test turingcomplete 192.168.1.2 NONEXPIRE

Elapsed time: 17 msecs
Running: env STEP=stepA_mal MAL_IMPL=js ../q/run ../tests/perf2.mal
KDB+ 3.6 2019.04.02 Copyright (C) 1993-2019 Kx Systems
l32/ 8()core 15892MB test turingcomplete 192.168.1.2 NONEXPIRE

Elapsed time: 71 msecs
Running: env STEP=stepA_mal MAL_IMPL=js ../q/run ../tests/perf3.mal
KDB+ 3.6 2019.04.02 Copyright (C) 1993-2019 Kx Systems
l32/ 8()core 15892MB test turingcomplete 192.168.1.2 NONEXPIRE

iters over 10 seconds: 244
```

**Comment by alimpfard** [comment]
And with that, all the `.travis_test.sh` tests mentioned in `.travis.yml` pass locally.

**Comment by alimpfard** [comment]
@kanaka @dubek 

_ping_

(been a month or so now, this poor pr could use some eyes on it)

**Comment by kanaka** [comment]
Hi @alimpfard. Sorry for the months long delay. I basically ended up taking a break from mal and open-source related stuff for past year or so.

I'm back to some degree and working through mal stuff that has piled up. I was looking at reviewing this and wasn't able to build the docker image because the executable wasn't able to be downloaded. I went to kx.com to try and find a updated download and have to agree to a non-commercial use license. This clause is a problem: "(b) No Distribution or Hosting. The User may not distribute or host the 32 Bit Kdb+ Software or User Applications to or for any third party." In order to publish the docker image and make this work for CI, we would need an exception from kx.com.

If still want to get this implementation into the tree and are willing to do a bit more followup, you will need to contact kx.com, explain what we are trying to do and why we need to build a docker image, and see if they will give us a exception for this use case. The benefit to them is that there product would be linked to from the Mal project (and we can put whatever disclaimer they want next to the listing as long as it's very brief). If you don't want to hassle with that, I would be happy to link to your Q repo and mention in parenthesis that it can't be included in the main tree due to licensing restrictions.

**Comment by alimpfard** [comment]
I don't mind contacting them, we'll see how that goes : )

**Comment by alimpfard** [comment]
It doesn't look like they're gonna be responding to my email, but I did see an interpreter in Java
I'll check if it's complete enough to run this, and if so, switch to that.
Otherwise I'll just close the PR :shrug:

**Comment by alimpfard** [comment]
[That interpreter](https://github.com/timestored/jq) is nowhere near complete enough to be able to run this, sadly.

**Comment by kanaka** [comment]
@alimpfard well, that's unfortunate. We were really needing an implementation that starts with the letter Q. Do you want me to link to your repo and branch from the README and mention that it works but requires a non-free manual download? E.g. link to this path: https://github.com/alimpfard/mal/tree/q/impls/q

**Comment by alimpfard** [comment]
That would be nice : )

**Comment by kanaka** [comment]
@alimpfard It was a busy week so I wasn't able to get to this until just now. I added a link on the main README.md so maybe that will give you some leverage to be able to get an exception. :-)

**Pull request closed without merging**
