### PR TITLE
zig: deallocate a varargs function after applying it

### PR DESCRIPTION
**Pull request by asarhaddon**
This fixes an occasional segmentation fault.

### CODE REVIEW

**Comment by kanaka** [comment]
@asarhaddon sorry for the really slow response on this. I had to make the following change to get things to build (the `/mal` directory gets mounted over when running in docker mode):

```patch
diff --git a/impls/zig/Dockerfile b/impls/zig/Dockerfile
index 0c6a79eb..024c91d4 100644
--- a/impls/zig/Dockerfile
+++ b/impls/zig/Dockerfile
@@ -20,7 +20,7 @@ WORKDIR /mal
 
 RUN apt-get -y install ca-certificates curl gcc libc-dev libpcre3-dev libreadline-dev xz-utils
 
-RUN curl https://ziglang.org/download/0.8.1/zig-linux-x86_64-0.8.1.tar.xz | tar -xJC/mal
-RUN ln -fst/usr/local/bin /mal/zig-linux-x86_64-0.8.1/zig
+RUN curl https://ziglang.org/download/0.8.1/zig-linux-x86_64-0.8.1.tar.xz | tar -xJC/opt
+RUN ln -fst /usr/local/bin /opt/zig-linux-x86_64-0.8.1/zig
 
 ENV HOME /mal
```

Then I started getting a segfault in step6:

```
$ make "docker-build^zig"
$ make DOCKERIZE=1 "test^zig^step6"
...
TEST: '(f)' -> ['',9] -> SUCCESS
Testing whether closures can retain atoms
TEST: '(def! g (let* (atm (atom 0)) (fn* () (deref atm))))' -> ['',]
Exception: IOError(5, 'Input/output error')
Output before exception:
(def! g (let* (atm (atom 0)) (fn* () (deref atm))))
Segmentation fault at address 0x0
/opt/zig-linux-x86_64-0.8.1/lib/std/hash_map.zig:863:33: 0x20e638 in std.hash_map.HashMap([]const u8,*types.MalType,std.hash_map.StringContext,80).get (step6_file)
            return self.header().capacity;
                                ^

make: *** [Makefile:238: test^zig^step6] Error 1

```

**Comment by asarhaddon** [comment]
In case this helps, a similar failure is visible with `make test^zig^stepA REGRESS=1` during step3 tests, even if step3 itself passes the tests.
@rjtobin are you in a position to investigate the segmentation faults with zig 0.8.1 and/or update for zig 0.14.0?

**Comment by asarhaddon** [comment]
I have rewritten large parts of the zig implementation, in order to fix the segmentation faults and merge eval_ast.
This should help with #657 and close #675.

**Comment by kanaka** [comment]
@asarhaddon The GHA failure is because the zig binary is under `/mal` which during builds is volume mounted over by the mal working directory. I think if you switch the location to `/opt` instead of `/mal` and symlink to it there it should work.

**Comment by kanaka** [comment]
@asarhaddon I had forgotten that I have the ability to add commits to a PR (even from others) directly via the UI. Since it was a fairly trivial change, I went ahead and made it and things all passed. Merged.

**Pull request merged**
