### PR TITLE
Merge eval and evalAST in purescript implementation

### PR DESCRIPTION
**Pull request by asarhaddon**
Hello.
These changes should be part of #592 , but

- the merge request adding the purescript implementation has been accepted before it,
- I had to update some settings for the latest purescript. @mrsekut, could you please review them ?.

### CODE REVIEW

**Review by mrsekut — APPROVED** [review]
LGTM!!!!

**Review by kanaka — CHANGES_REQUESTED** [review]
Looks like the Dockerfile needs to be updated. Probably something like this:
```
FROM ubuntu:24.04

##########################################################
# General requirements for testing or common across many
# implementations
##########################################################

RUN apt-get -y update

# Required for running tests
RUN apt-get -y install make python3
RUN ln -fs /usr/bin/python3 /usr/local/bin/python

RUN mkdir -p /mal
WORKDIR /mal

##########################################################
# Specific implementation requirements
##########################################################

RUN DEBIAN_FRONTEND=noninteractive apt-get -y install g++ libreadline-dev nodej
s npm

# Install purescript and deps
RUN apt-get install -y git libtinfo6
RUN npm install -g --unsafe-perm purescript spago

ENV NPM_CONFIG_CACHE /mal/.npm
ENV HOME /mal
```

**Comment by asarhaddon** [comment]
Now the build system complains that esbuild is not installed.

**Comment by kanaka** [comment]
Looks like that error can be resolved like this:
```
--- a/impls/purs/Makefile
+++ b/impls/purs/Makefile
@@ -9,7 +9,7 @@ OTHER_SRCS = src/Readline.js src/Readline.purs src/Types.purs src/Reader.purs \
 all: $(BINS)

 $(BINS): %.js: src/%.purs $(OTHER_SRCS) node_modules/readline-sync
-       spago bundle-app --main $($(<:src/%=%)) --to $@
+       spago bundle-app --platform=node --main $($(<:src/%=%)) --to $@


 node_modules/readline-sync:
 ```

**Comment by kanaka** [comment]
@asarhaddon I have no idea what's causing the most recent failure. I poked around a bit but didn't see anything obvious.

**Comment by asarhaddon** [comment]
The same error appears without the merge-eval, without readline and with argv, readString, writeString from the node-process module instead of a local FFI to javascript. I am giving up the update part.

**Comment by kanaka** [comment]
@asarhaddon works for me. There are a lot of implementations that could/should be updated from very old version of the docker image/compiler/interpreter. I'm fine with not doing that as part of these updates if it's proves problematic.

**Pull request merged**
