### PR TITLE
Update Rust code to the current Rust nightly

### PR DESCRIPTION
**Pull request by alexcrichton**
Lots of changes! Hopefully everything is still semantically equivalent (tests
still pass)

This is an alternative to #23

Note that I forked rust-pcre to https://github.com/alexcrichton/rust-pcre and updated it as well. My current compiler version is `rustc 1.0.0-nightly (fed12499e 2015-03-03) (built 2015-03-04)`

### CODE REVIEW

**Comment by alexcrichton** [comment]
I may not have run the tests correctly though, so you may wish to double check before merging!

**Comment by kanaka** [comment]
Awesome! The changes look really good and the main tests all pass, however, apparently I'm missing a test related to macros or quoting because `make perf^rust` and `make MAL_IMPL=rust test^mal` (self-hosted) fail with complaints about "splice-unquote".

I'll try and track it down later tonight (and add a test to the main suite to catch it), unless you get to it first. But I think we're pretty close. Thanks for your work on this!

**Comment by kanaka** [comment]
Simple reproducer:
```
user> (or (or false 4))
Error: 'splice-unquote' not found
```

Using macroexpand to debug:
```
user> (macroexpand (or (or false 4)))
(let* (or_FIXME false) (if or_FIXME or_FIXME (or (splice-unquote (rest xs)))))
```

Here's what it should be:
```
user> (macroexpand (or (or false 4)))
(let* (or_FIXME false) (if or_FIXME or_FIXME (or 4)))
```

I added a test for (or (or false 4))

**Comment by alexcrichton** [comment]
Oh oops! I pushed a commit which fixed a typo, not entirely sure how that got in there. It looks like `make perf^rust` now passes but `make MAL_IMPL=rust test^mal` has one failure:

```
TEST: (try* (throw (list "data" "foo")) (catch* exc (do (prn "err:" exc) 7))) -> ['"err:" ("data" "foo")\r\n','7'] -> FAIL (line 18):
    Expected : '(try* (throw (list "data" "foo")) (catch* exc (do (prn "err:" exc) 7)))\r\n"err:" ("data" "foo")\r\n7'
    Got      : '(try* (throw (list "data" "foo")) (catch* exc (do (prn "err:" exc) 7)) \r)\r\n"err:" ("data" "foo")\r\n7'
```

I wonder if I botched an update at some other location?

**Comment by kanaka** [comment]
@alexcrichton no, actually I think that's a pre-existing problem with the test runner (pseudo-pty mangling of long lines). I think we're good if that's the only error.

**Comment by steveklabnik** [comment]
Woo :confetti_ball:

**Comment by kanaka** [comment]
Verified and merged!

**Comment by alexcrichton** [comment]
Woohoo, thanks @kanaka!

**Comment by kanaka** [comment]
@alexcrichton @steveklabnik I also just pushed an update that applies the simplifications @alexcrichton  made in stepA to the other steps.

@alexcrichton thanks for doing the leg-work on this! The code looks much better. The try! macro is huge.

**Comment by alexcrichton** [comment]
>  Showing 11 changed files with 555 additions and 971 deletions. 

Now that's a nice diffstat!

**Comment by kanaka** [comment]
@alandipert yeah! A lot of that probably just reflects the fact that I'm a rust newbie, but certainly, improvements to rust have really helped. Progress all around :+1:

**Comment by kanaka** [comment]
https://twitter.com/bus_kanaka/status/573567869893525508

BTW, some of the mal implementors hang out at #mal (freenode) in case you're interested in discussions about mal, the make-a-lis process, Lisps, languages and whatever.

**Pull request merged**
